<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2019 v5.6.162
     Generated on:       5/12/2019 11:18 PM
     Generated by:       
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2019
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-QuickSwitch_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formEQSwitch = New-Object 'System.Windows.Forms.Form'
	$labelRunningEQInstances = New-Object 'System.Windows.Forms.Label'
	$listview1 = New-Object 'System.Windows.Forms.ListView'
	$textbox1 = New-Object 'System.Windows.Forms.TextBox'
	$buttonRefresh = New-Object 'System.Windows.Forms.Button'
	$menustrip1 = New-Object 'System.Windows.Forms.MenuStrip'
	$toolsToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$sortToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$AscendingToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$DescendingToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$NoneToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$resetToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$fontSizeToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$smallToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$mediumToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$largeToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$extraLargeToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$toolstripmenuitem1 = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$aboutToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$sourceLinkToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formEQSwitch_Load = {
		
		if (-not (Test-Path -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch))
		{
			New-Item -path HKCU:\SOFTWARE\EQSwitch -Force | Out-Null
		}
		$SavedWidth = Get-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch | Select-Object -ExpandProperty FormWidth -ErrorAction SilentlyContinue
		$SavedHeight = Get-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch | Select-Object -ExpandProperty FormHeight -ErrorAction SilentlyContinue
		$SavedPositionX = Get-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch | Select-Object -ExpandProperty FormPositionX -ErrorAction SilentlyContinue
		$SavedPositionY = Get-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch | Select-Object -ExpandProperty FormPositionY -ErrorAction SilentlyContinue
		$SavedFontSize = Get-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch | Select-Object -ExpandProperty ListViewFontSize -ErrorAction SilentlyContinue
		$SavedOrder = Get-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch | Select-Object -ExpandProperty ListViewOrder -ErrorAction SilentlyContinue
		if ($SavedWidth -ne $null) #set saved form width
		{
			$formEQSwitch.Width = $SavedWidth #set saved width
		}
		if ($SavedHeight -ne $null) #set saved form height
		{
			$formEQSwitch.Height = $SavedHeight #set saved height
		}
		if (($SavedPositionX -ne $null) -and ($SavedPositionY -ne $null)) #set saved form position
		{
			$formEQSwitch.Location = "$SavedPositionX, $SavedPositionY" #set saved position
		}
		if ($SavedFontSize -ne $null) #set saved font size
		{
			if ($SavedFontSize -match '7pt')
			{
				Set-SmallFont
			}
			elseif ($SavedFontSize -match '9pt')
			{
				Set-MediumFont
			}
			elseif ($SavedFontSize -match '11pt')
			{
				Set-LargeFont
			}
			elseif ($SavedFontSize -match '13pt')
			{
				Set-ExtraLargeFont
			}
			$textbox1.Font = $SavedFontSize
			$listview1.Font = $SavedFontSize
		}
		if (($SavedOrder -eq $null) -or ($SavedOrder -eq 'Ascending')) #set saved order
		{
			Set-Ascending
		}
		elseif ($SavedOrder -eq 'Descending')
		{
			Set-Descending
		}
		else
		{
			Set-None
		}
		#$tooltip1.InitialDelay = "20" #make tooltip show very fast default is 500ms
	}
	
	#region Control Helper Functions
	function Update-ListViewColumnSort
	{
	<#
		.SYNOPSIS
			Sort the ListView's item using the specified column.
		
		.DESCRIPTION
			Sort the ListView's item using the specified column.
			This function uses Add-Type to define a class that sort the items.
			The ListView's Tag property is used to keep track of the sorting.
		
		.PARAMETER ListView
			The ListView control to sort.
		
		.PARAMETER ColumnIndex
			The index of the column to use for sorting.
		
		.PARAMETER SortOrder
			The direction to sort the items. If not specified or set to None, it will toggle.
		
		.EXAMPLE
			Update-ListViewColumnSort -ListView $listview1 -ColumnIndex 0
		
		.NOTES
			Additional information about the function.
	#>
		
		param
		(
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			[System.Windows.Forms.ListView]$ListView,
			[Parameter(Mandatory = $true)]
			[int]$ColumnIndex,
			[System.Windows.Forms.SortOrder]$SortOrder = 'None'
		)
		
		if (($ListView.Items.Count -eq 0) -or ($ColumnIndex -lt 0) -or ($ColumnIndex -ge $ListView.Columns.Count))
		{
			return;
		}
		
		#region Define ListViewItemComparer
		try
		{
			[ListViewItemComparer] | Out-Null
		}
		catch
		{
			Add-Type -ReferencedAssemblies ('System.Windows.Forms') -TypeDefinition @" 
	using System;
	using System.Windows.Forms;
	using System.Collections;
	public class ListViewItemComparer : IComparer
	{
	    public int column;
	    public SortOrder sortOrder;
	    public ListViewItemComparer()
	    {
	        column = 0;
			sortOrder = SortOrder.Ascending;
	    }
	    public ListViewItemComparer(int column, SortOrder sort)
	    {
	        this.column = column;
			sortOrder = sort;
	    }
	    public int Compare(object x, object y)
	    {
			if(column >= ((ListViewItem)x).SubItems.Count)
				return  sortOrder == SortOrder.Ascending ? -1 : 1;
		
			if(column >= ((ListViewItem)y).SubItems.Count)
				return sortOrder == SortOrder.Ascending ? 1 : -1;
		
			if(sortOrder == SortOrder.Ascending)
	        	return String.Compare(((ListViewItem)x).SubItems[column].Text, ((ListViewItem)y).SubItems[column].Text);
			else
				return String.Compare(((ListViewItem)y).SubItems[column].Text, ((ListViewItem)x).SubItems[column].Text);
	    }
	}
"@ | Out-Null
		}
		#endregion
		
		if ($ListView.Tag -is [ListViewItemComparer])
		{
			#Toggle the Sort Order
			if ($SortOrder -eq [System.Windows.Forms.SortOrder]::None)
			{
				if ($ListView.Tag.column -eq $ColumnIndex -and $ListView.Tag.sortOrder -eq 'Ascending')
				{
					$ListView.Tag.sortOrder = 'Descending'
				}
				else
				{
					$ListView.Tag.sortOrder = 'Ascending'
				}
			}
			else
			{
				$ListView.Tag.sortOrder = $SortOrder
			}
			
			$ListView.Tag.column = $ColumnIndex
			$ListView.Sort() #Sort the items
		}
		else
		{
			if ($SortOrder -eq [System.Windows.Forms.SortOrder]::None)
			{
				$SortOrder = [System.Windows.Forms.SortOrder]::Ascending
			}
			
			#Set to Tag because for some reason in PowerShell ListViewItemSorter prop returns null
			$ListView.Tag = New-Object ListViewItemComparer ($ColumnIndex, $SortOrder)
			$ListView.ListViewItemSorter = $ListView.Tag #Automatically sorts
		}
	}
	
	function Add-ListViewItem
	{
	<#
		.SYNOPSIS
			Adds the item(s) to the ListView and stores the object in the ListViewItem's Tag property.
	
		.DESCRIPTION
			Adds the item(s) to the ListView and stores the object in the ListViewItem's Tag property.
	
		.PARAMETER ListView
			The ListView control to add the items to.
	
		.PARAMETER Items
			The object or objects you wish to load into the ListView's Items collection.
			
		.PARAMETER  ImageIndex
			The index of a predefined image in the ListView's ImageList.
		
		.PARAMETER  SubItems
			List of strings to add as Subitems.
		
		.PARAMETER Group
			The group to place the item(s) in.
		
		.PARAMETER Clear
			This switch clears the ListView's Items before adding the new item(s).
		
		.EXAMPLE
			Add-ListViewItem -ListView $listview1 -Items "Test" -Group $listview1.Groups[0] -ImageIndex 0 -SubItems "Installed"
	#>
		
		Param (
			[ValidateNotNull()]
			[Parameter(Mandatory = $true)]
			[System.Windows.Forms.ListView]$ListView,
			[ValidateNotNull()]
			[Parameter(Mandatory = $true)]
			$Items,
			[int]$ImageIndex = -1,
			[string[]]$SubItems,
			$Group,
			[switch]$Clear)
		
		if ($Clear)
		{
			$ListView.Items.Clear();
		}
		
		$lvGroup = $null
		if ($Group -is [System.Windows.Forms.ListViewGroup])
		{
			$lvGroup = $Group
		}
		elseif ($Group -is [string])
		{
			#$lvGroup = $ListView.Group[$Group] # Case sensitive
			foreach ($groupItem in $ListView.Groups)
			{
				if ($groupItem.Name -eq $Group)
				{
					$lvGroup = $groupItem
					break
				}
			}
			
			if ($null -eq $lvGroup)
			{
				$lvGroup = $ListView.Groups.Add($Group, $Group)
			}
		}
		
		if ($Items -is [Array])
		{
			$ListView.BeginUpdate()
			foreach ($item in $Items)
			{
				$listitem = $ListView.Items.Add($item.ToString(), $ImageIndex)
				#Store the object in the Tag
				$listitem.Tag = $item
				
				if ($null -ne $SubItems)
				{
					$listitem.SubItems.AddRange($SubItems)
				}
				
				if ($null -ne $lvGroup)
				{
					$listitem.Group = $lvGroup
				}
			}
			$ListView.EndUpdate()
		}
		else
		{
			#Add a new item to the ListView
			$listitem = $ListView.Items.Add($Items.ToString(), $ImageIndex)
			#Store the object in the Tag
			$listitem.Tag = $Items
			
			if ($null -ne $SubItems)
			{
				$listitem.SubItems.AddRange($SubItems)
			}
			
			if ($null -ne $lvGroup)
			{
				$listitem.Group = $lvGroup
			}
		}
	}
	
	#endregion
	
	#region Show-Process
	#https://community.idera.com/database-tools/powershell/powertips/b/tips/posts/bringing-window-in-the-foreground
	function Show-Process($Process, [Switch]$Maximize)
	{
		$sig = '
    [DllImport("user32.dll")] public static extern bool ShowWindowAsync(IntPtr hWnd, int nCmdShow);
    [DllImport("user32.dll")] public static extern int SetForegroundWindow(IntPtr hwnd);
  '
		
		if ($Maximize) { $Mode = 3 }
		else { $Mode = 4 }
		$type = Add-Type -MemberDefinition $sig -Name WindowAPI -PassThru
		$hwnd = $process.MainWindowHandle
		$null = $type::ShowWindowAsync($hwnd, $Mode)
		$null = $type::SetForegroundWindow($hwnd)
	}
	#endregion Show-Process
	
	#region buttonup
	function buttonup
	{
		$this.Cursor = 'Default'
		$this.Enabled = $true
	}
	#endregion buttonup
	
	#region buttondown
	function buttondown
	{
		$this.Cursor = 'WaitCursor'
		$this.Enabled = $false
	}
	#endregion buttondown
	
	#region Set-FormSize
	function Set-FormSize
	{
		if (Test-Path -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch)
		{
			Set-ItemProperty -path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch -Name FormWidth -Value $formEQSwitch.Width #set FormWidth
			Set-ItemProperty -path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch -Name FormHeight -Value $formEQSwitch.Height #set FormHeight
		}
	}
	#endregion Set-FormSize
	
	#region Set-FormPosition
	function Set-FormPosition
	{
		if (Test-Path -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch)
		{
			#Must use string with a negative number
			Set-ItemProperty -path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch -Name FormPositionX -Value $formEQSwitch.Location.X -Type String #set FormPosition X
			Set-ItemProperty -path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch -Name FormPositionY -Value $formEQSwitch.Location.y -Type String #set FormPosition Y
		}
	}
	#endregion Set-FormPosition
	
	#region Set-ToolMenuOptions
	function Set-Ascending
	{
		$AscendingToolStripMenuItem.Checked = $true
		$DescendingToolStripMenuItem.Checked = $false
		$NoneToolStripMenuItem.Checked = $false
		$listview1.Sorting = 'Ascending'
	}
	
	function Set-Descending
	{
		$AscendingToolStripMenuItem.Checked = $false
		$DescendingToolStripMenuItem.Checked = $true
		$NoneToolStripMenuItem.Checked = $false
		$listview1.Sorting = 'Descending'
	}
	
	function Set-None
	{
		$AscendingToolStripMenuItem.Checked = $false
		$DescendingToolStripMenuItem.Checked = $false
		$NoneToolStripMenuItem.Checked = $true
		$listview1.Sorting = 'None'
	}
	
	function Set-SmallFont
	{
		$smallToolStripMenuItem.Checked = $true
		$mediumToolStripMenuItem.Checked = $false
		$largeToolStripMenuItem.Checked = $false
		$extraLargeToolStripMenuItem.Checked = $false
		$textbox1.Font = 'Microsoft Sans Serif, 7pt'
		$listview1.Font = 'Microsoft Sans Serif, 7pt'
	}
	
	function Set-MediumFont
	{
		$smallToolStripMenuItem.Checked = $false
		$mediumToolStripMenuItem.Checked = $true
		$largeToolStripMenuItem.Checked = $false
		$extraLargeToolStripMenuItem.Checked = $false
		$textbox1.Font = 'Microsoft Sans Serif, 9pt'
		$listview1.Font = 'Microsoft Sans Serif, 9pt'
	}
	
	function Set-LargeFont
	{
		$smallToolStripMenuItem.Checked = $false
		$mediumToolStripMenuItem.Checked = $false
		$largeToolStripMenuItem.Checked = $true
		$extraLargeToolStripMenuItem.Checked = $false
		$textbox1.Font = 'Microsoft Sans Serif, 11pt'
		$listview1.Font = 'Microsoft Sans Serif, 11pt'
	}
	
	function Set-ExtraLargeFont
	{
		$smallToolStripMenuItem.Checked = $false
		$mediumToolStripMenuItem.Checked = $false
		$largeToolStripMenuItem.Checked = $false
		$extraLargeToolStripMenuItem.Checked = $true
		$textbox1.Font = 'Microsoft Sans Serif, 13pt'
		$listview1.Font = 'Microsoft Sans Serif, 13pt'
	}
	
	#endregion Set-ToolMenuOptions
	
	#region Show-MsgBox
	function script:Show-MsgBox
	{
		
		[CmdletBinding()]
		param (
			[Parameter(Position = 0, Mandatory = $true)]
			[string]$Prompt,
			[Parameter(Position = 1, Mandatory = $false)]
			[string]$Title = "",
			[Parameter(Position = 2, Mandatory = $false)]
			[ValidateSet("Information", "Question", "Critical", "Exclamation")]
			[string]$Icon = "Information",
			[Parameter(Position = 3, Mandatory = $false)]
			[ValidateSet("OKOnly", "OKCancel", "AbortRetryIgnore", "YesNoCancel", "YesNo", "RetryCancel")]
			[string]$BoxType = "OkOnly",
			[Parameter(Position = 4, Mandatory = $false)]
			[ValidateSet(1, 2, 3)]
			[int]$DefaultButton = 1
		)
		[System.Reflection.Assembly]::LoadWithPartialName("Microsoft.VisualBasic") | Out-Null
		switch ($Icon)
		{
			"Question" { $vb_icon = [microsoft.visualbasic.msgboxstyle]::Question }
			"Critical" { $vb_icon = [microsoft.visualbasic.msgboxstyle]::Critical }
			"Exclamation" { $vb_icon = [microsoft.visualbasic.msgboxstyle]::Exclamation }
			"Information" { $vb_icon = [microsoft.visualbasic.msgboxstyle]::Information }
		}
		switch ($BoxType)
		{
			"OKOnly" { $vb_box = [microsoft.visualbasic.msgboxstyle]::OKOnly }
			"OKCancel" { $vb_box = [microsoft.visualbasic.msgboxstyle]::OkCancel }
			"AbortRetryIgnore" { $vb_box = [microsoft.visualbasic.msgboxstyle]::AbortRetryIgnore }
			"YesNoCancel" { $vb_box = [microsoft.visualbasic.msgboxstyle]::YesNoCancel }
			"YesNo" { $vb_box = [microsoft.visualbasic.msgboxstyle]::YesNo }
			"RetryCancel" { $vb_box = [microsoft.visualbasic.msgboxstyle]::RetryCancel }
		}
		switch ($Defaultbutton)
		{
			1 { $vb_defaultbutton = [microsoft.visualbasic.msgboxstyle]::DefaultButton1 }
			2 { $vb_defaultbutton = [microsoft.visualbasic.msgboxstyle]::DefaultButton2 }
			3 { $vb_defaultbutton = [microsoft.visualbasic.msgboxstyle]::DefaultButton3 }
		}
		$popuptype = $vb_icon -bor $vb_box -bor $vb_defaultbutton
		$ans = [Microsoft.VisualBasic.Interaction]::MsgBox($prompt, $popuptype, $title)
		return $ans
	}
	#endregion Show-MsgBox
	
	$buttonRefresh_Click = {
		buttondown
		$listview1.Clear()
		$textbox1.Clear()
		$SavedOrder = Get-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch | Select-Object -ExpandProperty ListViewOrder -ErrorAction SilentlyContinue
		$Script:RunningEQ = get-process -Name eqgame
		$unique = $RunningEQ | Select-Object -Property MainWindowTitle -Unique
		<#
		if ($RunningEQ.count -eq $unique) #check for duplicate process names
		{
			$ContainsDuplicates = $false
			$Script:RunningEQTitles = $RunningEQ.MainWindowTitle
		}
		else
		{
			$ContainsDuplicates = $true
			$list = @()
			foreach ($r in $RunningEQ)
			{			
				$list += [PSCUSTOMOBJECT] @{
					Name = $r.MainWindowTitle
					ID   = $r.Id
				}			
			}		
		}#>
		$Script:RunningEQTitles = $RunningEQ.MainWindowTitle
		$textbox1.AutoCompleteCustomSource.AddRange($RunningEQTitles)
		$labelRunningEQInstances.Text = "EQ Processes:  $($RunningEQTitles.Count)"
		#$maxlength = ($RunningEQTitles | Measure-Object -Maximum -Property Length).Maximum
		if (($SavedOrder -eq $null) -or ($SavedOrder -eq 'Ascending'))
		{
			Set-Ascending
		}
		elseif ($SavedOrder -eq 'Descending')
		{
			Set-Descending
		}
		else
		{
			Set-None
		}
		Add-ListViewItem -ListView $listview1 -Items $RunningEQTitles
		buttonup
	}
	
	$textbox1_KeyDown = [System.Windows.Forms.KeyEventHandler]{
		#Event Argument: $_ = [System.Windows.Forms.KeyEventArgs]
		if ($_.KeyCode -eq 'Enter')
		{
			$ToonClick = $RunningEQ | Where-Object { $_.MainWindowTitle -eq $textbox1.Text }
			Show-Process -Process $ToonClick
		}
	}
	
	$textbox1_Click = {
		$textbox1.SelectAll()
	}
	
	$listview1_Click = {
		foreach ($item in $listview1.SelectedItems)
		{
			$textbox1.Text = $item.Text
			$ToonClick = $RunningEQ | Where-Object { $_.MainWindowTitle -eq $item.Text }
			Show-Process -Process $ToonClick
		}
	}
	
	$formEQSwitch_Resize = {
		Set-FormSize
	}
	
	$formEQSwitch_Move = {
		Set-FormPosition
	}
	
	$AscendingToolStripMenuItem_Click = {
		Set-Ascending
		Set-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch -Name ListViewOrder -Value Ascending
	}
	
	$DescendingToolStripMenuItem_Click = {
		Set-Descending
		Set-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch -Name ListViewOrder -Value Descending
	}
	
	$NoneToolStripMenuItem_Click = {
		Set-None
		Set-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch -Name ListViewOrder -Value None
		$buttonRefresh.PerformClick() #required to refresh listview
	}
	
	$smallToolStripMenuItem_Click = {
		Set-SmallFont
		Set-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch -Name ListViewFontSize -Value 'Microsoft Sans Serif, 7pt'
	}
	
	$mediumToolStripMenuItem_Click = {
		Set-MediumFont
		Set-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch -Name ListViewFontSize -Value 'Microsoft Sans Serif, 9pt'
	}
	
	$largeToolStripMenuItem_Click = {
		Set-LargeFont
		Set-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch -Name ListViewFontSize -Value 'Microsoft Sans Serif, 11pt'
	}
	
	$extraLargeToolStripMenuItem_Click = {
		Set-ExtraLargeFont
		Set-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch -Name ListViewFontSize -Value 'Microsoft Sans Serif, 13pt'
	}
	
	$resetToolStripMenuItem_Click = {
		$formEQSwitch.Location = "0, 0"
		$formEQSwitch.Width = 161
		$formEQSwitch.Height = 723
		#Set-Ascending
		#Set-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch -Name ListViewOrder -Value Ascending
		#Set-MediumFont
		#Set-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\EQSwitch -Name ListViewFontSize -Value Medium
		$AscendingToolStripMenuItem.PerformClick()
		$mediumToolStripMenuItem.PerformClick()
		Set-FormPosition
		Set-FormSize
	}
	
	$aboutToolStripMenuItem_Click = {
		Show-MsgBox -Title 'About EQSwitch' -Prompt 'EQSwitch is provided as-is, without any warranty.  Please report any bugs to Zuboo on PEQ.  EQSwitch does not function with duplicate process names.  Make sure every EQ process is named after your toon.' -BoxType OKOnly -Icon Information
	}
	
	$sourceLinkToolStripMenuItem_Click = {
		Start-process 'https://github.com/OverturnedStone/Everquest/tree/master/EQSwitch'
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formEQSwitch.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$listview1.remove_Click($listview1_Click)
			$textbox1.remove_Click($textbox1_Click)
			$textbox1.remove_KeyDown($textbox1_KeyDown)
			$buttonRefresh.remove_Click($buttonRefresh_Click)
			$formEQSwitch.remove_Load($formEQSwitch_Load)
			$formEQSwitch.remove_Move($formEQSwitch_Move)
			$formEQSwitch.remove_Resize($formEQSwitch_Resize)
			$AscendingToolStripMenuItem.remove_Click($AscendingToolStripMenuItem_Click)
			$DescendingToolStripMenuItem.remove_Click($DescendingToolStripMenuItem_Click)
			$NoneToolStripMenuItem.remove_Click($NoneToolStripMenuItem_Click)
			$resetToolStripMenuItem.remove_Click($resetToolStripMenuItem_Click)
			$smallToolStripMenuItem.remove_Click($smallToolStripMenuItem_Click)
			$mediumToolStripMenuItem.remove_Click($mediumToolStripMenuItem_Click)
			$largeToolStripMenuItem.remove_Click($largeToolStripMenuItem_Click)
			$extraLargeToolStripMenuItem.remove_Click($extraLargeToolStripMenuItem_Click)
			$aboutToolStripMenuItem.remove_Click($aboutToolStripMenuItem_Click)
			$sourceLinkToolStripMenuItem.remove_Click($sourceLinkToolStripMenuItem_Click)
			$formEQSwitch.remove_Load($Form_StateCorrection_Load)
			$formEQSwitch.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formEQSwitch.SuspendLayout()
	$menustrip1.SuspendLayout()
	#
	# formEQSwitch
	#
	$formEQSwitch.Controls.Add($labelRunningEQInstances)
	$formEQSwitch.Controls.Add($listview1)
	$formEQSwitch.Controls.Add($textbox1)
	$formEQSwitch.Controls.Add($buttonRefresh)
	$formEQSwitch.Controls.Add($menustrip1)
	$formEQSwitch.AutoScaleDimensions = '6, 13'
	$formEQSwitch.AutoScaleMode = 'Font'
	$formEQSwitch.BackColor = 'Control'
	$formEQSwitch.ClientSize = '145, 684'
	$formEQSwitch.ForeColor = 'ActiveCaptionText'
	$formEQSwitch.FormBorderStyle = 'SizableToolWindow'
	#region Binary Data
	$formEQSwitch.Icon = [System.Convert]::FromBase64String('
AAABAAcAQEAAAAEAIAAoQgAAdgAAADAwAAABACAAqCUAAJ5CAAAoKAAAAQAgAGgaAABGaAAAICAA
AAEAIACoEAAAroIAABgYAAABACAAiAkAAFaTAAAUFAAAAQAgALgGAADenAAAEBAAAAEAIABoBAAA
lqMAACgAAABAAAAAgAAAAAEAIAAAAAAAAEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAACFrUsGha1LDIWtSwyFrUsIAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1LB4WtS0GFrUt+ha1LqIWtS8+FrUvwha1L/4WtS/+F
rUv/ha1L/4WtS/aFrUvXha1LsIWtS4iFrUtPha1LEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtSwmFrUtXha1LtIWtS/aF
rUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4Wt
S/yFrUvGha1LbIWtSxQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAha1LGoWtS4yFrUvwha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4Wt
S/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv5ha1LpYWtSy8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFrUsOha1LiYWtS/aFrUv/ha1L/4WtS/+FrUv/ha1L/4Wt
S/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L
/4WtS/+FrUv/ha1L/4WtS/+FrUv9ha1LqIWtSx8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFrUtQha1L5YWt
S/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L
/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv1
ha1Lc4WtSwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAIWtSwiFrUubha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L
/4WtS/+FrUv/ha1L/5K2X/+dvW//o8F4/6XCev+fvnH/lrhk/4auTf+FrUv/ha1L/4WtS/+FrUv/
ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUu6ha1LFgAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtSxqFrUvMha1L/4WtS/+FrUv/ha1L
/4WtS/+FrUv/ha1L/4WtS/+FrUv/h65O/6bDfP/J27D/5e7a//r79///////////////////////
///////////8/fv/6vHh/9Dfuv+uyYj/i7FU/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+F
rUv/ha1L/4WtS+WFrUs2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AIWtSyaFrUvhha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+TtmD/x9mt//X48P//////
//////////////////////////////////////////////////////////////////////r8+P/S
4b3/nb1u/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L9YWtS0gAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtSySFrUvmha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/
ha1L/42yV//L3LP//P36////////////////////////////////////////////////////////
//////////////////////////////////////////7+/v/a5sj/lrhk/4WtS/+FrUv/ha1L/4Wt
S/+FrUv/ha1L/4WtS/+FrUv4ha1LSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtSxeFrUve
ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/67JiP/0+O//////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////v8+f/A1aP/hq5N/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/WFrUs3AAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAIWtSwaFrUvGha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/iK9Q/87et///
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////+Dq0v+QtFz/ha1L
/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L54WtSxoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFrUuPha1L/4WtS/+F
rUv/ha1L/4WtS/+FrUv/jLFV/+Dq0f//////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////7/Tn/5a5Zf+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUvC
ha1LAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAACFrUtCha1L/YWtS/+FrUv/ha1L/4WtS/+FrUv/jLJW/+bu2///////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////09+//
mLpn/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS3cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFrUsHha1L24WtS/+FrUv/ha1L/4Wt
S/+FrUv/h65P/+Dq0f//////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////H16v+RtVz/ha1L/4WtS/+FrUv/ha1L/4WtS/+F
rUv2ha1LIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAha1LdoWtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/8vcs///////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////Pz8//Pz8///////////////////
////4+zW/4euTv+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS6wAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1LDoWtS+2FrUv/ha1L/4WtS/+FrUv/ha1L
/6nFgP/+/v7/////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////0NDQ/3p6ev+srKz////////////////////////////D1qb/ha1L/4WtS/+FrUv/ha1L/4Wt
S/+FrUv+ha1LMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AIWtS3WFrUv/ha1L/4WtS/+FrUv/ha1L/4qwUv/v9Oj/////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////39/f/np6e/2hoaP9qamr/5+fn////////////////////
/////////P37/5m6af+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS6oAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtSwKFrUveha1L/4WtS/+FrUv/ha1L/4WtS//B1aT/
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////l5eX/f39//2ho
aP9oaGj/qqqq///////////////////////////////////////c58z/ha1L/4WtS/+FrUv/ha1L
/4WtS/+FrUv7ha1LGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFrUtD
ha1L/4WtS/+FrUv/ha1L/4WtS/+LsVT/9vny////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////Q0ND/b29v/2hoaP9oaGj/e3t7//j4+P//////////////////////////
/////////////v7+/5++cv+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS3kAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1LmoWtS/+FrUv/ha1L/4WtS/+FrUv/u9Gb////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////+5ubn/aWlp/2hoaP9oaGj/ampq
/9vb2//////////////////////////////////////////////////V48H/ha1L/4WtS/+FrUv/
ha1L/4WtS/+FrUvPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtS+OF
rUv/ha1L/4WtS/+FrUv/ha1L/+rx4P//////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//39/f+mpqb/aGho/2hoaP9oaGj/aGho/7S0tP//////////////////////////////////////
////////////////+/z6/42yVv+FrUv/ha1L/4WtS/+FrUv/ha1L/oWtSxwAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAIWtSyWFrUv/ha1L/4WtS/+FrUv/ha1L/5i5Z///////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////j4+P+VlZX/aGho/2hoaP9oaGj/aGho/5GRkf/9/f3/
//////////////////////////////////////////////////////////+yy43/ha1L/4WtS/+F
rUv/ha1L/4WtS/+FrUtbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFrUtdha1L/4Wt
S/+FrUv/ha1L/4WtS/+60Jn/////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////Hx8f+Ghob/
aGho/2hoaP9oaGj/aGho/3p6ev/z8/P/////////////////////////////////////////////
////////////////////0+G+/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1LkwAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAha1LioWtS/+FrUv/ha1L/4WtS/+FrUv/1ePC////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////+3t7f9/f3//aGho/2hoaP9oaGj/aGho/21tbf/g4OD/////////////
/////////////////////////////////////////////////////////+/06P+FrUv/ha1L/4Wt
S/+FrUv/ha1L/4WtS8EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtS62FrUv/ha1L
/4WtS/+FrUv/ha1L/+vx4v//////////////////////////////////////////////////////
/////////////////////////////////////////////////////+np6f96enr/aGho/2hoaP9o
aGj/aGho/2hoaP/Kysr/////////////////////////////////////////////////////////
///////////////////+/v7/i7FU/4WtS/+FrUv/ha1L/4WtS/+FrUvlAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAACFrUvIha1L/4WtS/+FrUv/ha1L/4WtS//7/Pn/////////////////
////////////////////////////////////////////////////////////////////////////
/////////+np6f93d3f/aGho/2hoaP9oaGj/aGho/2hoaP+xsbH/////////////////////////
/////////////////////////////////////////////////////////////5u8bP+FrUv/ha1L
/4WtS/+FrUv/ha1L/IWtSwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1L2oWtS/+FrUv/
ha1L/4WtS/+MsVX/////////////////////////////////////////////////////////////
//////////////////////////////////////////b29v98fHz/aGho/2hoaP9oaGj/aGho/2ho
aP+fn5///v7+////////////////////////////////////////////////////////////////
//////////////////////+lw3v/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUsRAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAIWtS+KFrUv/ha1L/4WtS/+FrUv/kLVc////////////////////////
////////////////////////////////////////////////////////////////////////////
///AwMD/aGho/2hoaP9oaGj/aGho/2hoaP+RkZH/+/v7////////////////////////////////
////////////////////////////////////////////////////////////q8aD/4WtS/+FrUv/
ha1L/4WtS/+FrUv/ha1LGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADi69Rz////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////urq6/2hoaP9oaGj/aGho/2hoaP+NjY3/9/f3
////////////////////////////////////////////////////////////////////////////
/////////////////////6rGgv+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtSxgAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA8vbtaf//////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/7q6uv9oaGj/aGho/2hoaP9oaGj/0NDQ////////////////////////////////////////////
//////////////////////////////////////////////////////////+kwnn/ha1L/4WtS/+F
rUv/ha1L/4WtS/+FrUsPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///1b/////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////BwcH/aGho/2hoaP9oaGj/aGho/9TU1P//////
////////////////////////////////////////////////////////////////////////////
////////////////////mbpp/4WtS/+FrUv/ha1L/4WtS/+FrUv6ha1LAQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAD///86////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
y8vL/2hoaP9oaGj/aGho/2hoaP/a2tr/////////////////////////////////////////////
/////////////////////////////////////////////////////f79/4mwUf+FrUv/ha1L/4Wt
S/+FrUv/ha1L4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////E/////7/////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////9XV1f9oaGj/aGho/2hoaP9oaGj/4uLi////////
////////////////////////////////////////////////////////////////////////////
/////////////+vy4v+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS7sAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAD////j////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////h
4eH/aGho/2hoaP9oaGj/aGho/+rq6v//////////////////////////////////////////////
///////////////////////////////////////////////////P37j/ha1L/4WtS/+FrUv/ha1L
/4WtS/+FrUuMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACyy44K6fDfrvn79v/5+/b/
+fv2//n79v/5+/b/+fv2//n79v/5+/b/+fv2//n79v/5+/b/+fv2//n79v/6/Pj/////////////
////////////////////////////////////7u7u/2hoaP9oaGj/aGho/2hoaP/09PT/////////
////////////////////////////////////////////////////////////////////////////
////////////rMeF/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1LUwAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAACKsFILha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+F
rUv/ha1L/4WtS/+FrUv/iK9P/9nmyP////////////////////////////////////////////v7
+/9oaGj/aGho/2hoaP9paWn//f39////////////////////////////////////////////////
////////////////////////////////////////////+fv2/4mwUv+FrUv/ha1L/4WtS/+FrUv/
ha1L/IWtSxMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1MDIWtS/+FrUv/ha1L/4WtS/+F
rUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+Ir1D/3ejN////
////////////////////////////////////////dXV1/2hoaP9oaGj/dHR0////////////////
////////////////////////////////////////////////////////////////////////////
/////87etv+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS8MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAIWtSwuFrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4Wt
S/+FrUv/ha1L/4WtS/+FrUv/ha1L/4qwUv/n7tv/////////////////////////////////////
/4WFhf9oaGj/aGho/4CAgP//////////////////////////////////////////////////////
//////////////////////////////////////3+/f+Yumf/ha1L/4WtS/+FrUv/ha1L/4WtS/+F
rUtsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFrUsLha1L/4WtS/+FrUv/ha1L/4Wt
S/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/k7Zf
/+/05/////////////////////////////////+Wlpb/aGho/2hoaP+Ojo7/////////////////
///////////////////////////////////////////////////////////////////////////T
4b7/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv2ha1LEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAha1LC4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L
/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+Ut2L/8fbr////////////////////////////
qqqq/2hoaP9oaGj/np6e////////////////////////////////////////////////////////
///////////////////////////////5+/b/k7Zf/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1LmgAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtSwqFrUv/ha1L/4WtS/+FrUv/ha1L
/4WtS/+FrUv/ha1L/4WtS/+FrUv/irBT/4uxVP+LsVT/i7FU/4uxVP+LsVT/i7FU/4uxVP+Hrk7/
ha1L/6XCev///////////////////////////76+vv9oaGj/aGho/7CwsP//////////////////
////////////////////////////////////////////////////////////////////ts6U/4Wt
S/+FrUv/ha1L/4WtS/+FrUv/ha1L+oWtSyQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAACFrUsHha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/7zSnf//////
///////////////////////////////////////////////////////////////////////////U
1NT/aGho/2hoaP/CwsL/////////////////////////////////////////////////////////
////////////////////////1uPD/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS5gAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1LB4WtS/+FrUv/ha1L/4WtS/+FrUv/
ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/1OLA////////////////////////////////////////
////////////////////////////////////7+/v/2hoaP9oaGj/2dnZ////////////////////
////////////////////////////////////////////////////////6PDe/4uxVP+FrUv/ha1L
/4WtS/+FrUv/ha1L/4WtS+2FrUsWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAIWtSweFrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4euT//b
5sr/////////////////////////////////////////////////////////////////////////
//92dnb/aGho//T09P//////////////////////////////////////////////////////////
////////////6/Lj/5C0XP+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUtgAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFrUsHha1L/4WtS/+FrUv/ha1L/4WtS/+F
rUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/h65O/9Lhvf//////////////////////////////
////////////////////////////////////////np6e/4GBgf//////////////////////////
////////////////////////////////////////////5e3Z/46zWf+FrUv/ha1L/4WtS/+FrUv/
ha1L/4WtS/+FrUurAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAha1LBYWtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS7qFrUv/ha1L/4WtS/+FrUv/ha1L/4Wt
S/+FrUv/vdOe//z9+///////////////////////////////////////////////////////////
/97e3v/Gxsb/////////////////////////////////////////////////////////////////
0eC7/4qwUv+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUvYha1LDgAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtSwOFrUv/ha1L/4WtS/+FrUv/ha1L/4Wt
S/+FrUsZha1Ly4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+gv3P/6vHg////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////09+//sMqL/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+F
rUvqha1LIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AACFrUsDha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1LC4WtSxSFrUvUha1L/4WtS/+FrUv/ha1L
/4WtS/+FrUv/ha1L/4euTv+70Zr/8/ft////////////////////////////////////////////
//////////////////////////////////////////////////////r79//I2q//jLJW/4WtS/+F
rUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUvtha1LMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1LA4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L
/4WtSwsAAAAAha1LFIWtS8yFrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4mvUf+2zpP/
5O3X//7+/v//////////////////////////////////////////////////////////////////
////7fPl/8HVo/+Ps1n/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUvoha1LMAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AIWtSwOFrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUsLAAAAAAAAAACFrUsMha1LsYWtS/+FrUv/
ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+WuGT/udCY/9Xjwv/s8uP//P37////////
///////////////+/v3/8PXq/9vnyv+/1KH/nr5w/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4Wt
S/+FrUv/ha1L/4WtS/+FrUvSha1LIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1Ld4WtS/+FrUv/ha1L/4WtS/+FrUv/
ha1LCAAAAAAAAAAAAAAAAIWtSwGFrUt4ha1L+oWtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+F
rUv/ha1L/4WtS/+FrUv/ha1L/4atTf+Os1n/lbhj/5e5Zf+QtFv/h65P/4WtS/+FrUv/ha1L/4Wt
S/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUugha1LCwAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAACFrUtdha1L+IWtS/+FrUv/ha1L/4WtSwcAAAAAAAAAAAAAAAAAAAAAAAAAAIWtSzGF
rUvHha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4Wt
S/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L
/4WtS+CFrUtPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtS0uFrUv3ha1L/4WtS/+F
rUsHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1LAYWtS2SFrUviha1L/4WtS/+FrUv/ha1L/4Wt
S/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L
/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L8YWtS4OFrUsKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAha1LSIWtS/aFrUv/ha1LBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAha1LBoWtS2WFrUvXha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L
/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUvoha1LfoWtSxEAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFrUtCha1L9IWt
SwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtSzyFrUuTha1L
24WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/
ha1L6IWtS6WFrUtQha1LBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtSyQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFrUseha1LXYWtS4yFrUuxha1LzoWtS+GFrUvp
ha1L7IWtS+OFrUvSha1LuIWtS5WFrUtoha1LLIWtSwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA/////////////////////////////////////D////////8AAP//////+AAA
H//////gAAAH/////4AAAAH/////AAAAAH////wAAAAAP///+AAAAAAf///wAAAAAA///+AAAAAA
B///wAAAAAAD//+AAAAAAAH//4AAAAAAAP//AAAAAAAA//4AAAAAAAB//gAAAAAAAH/8AAAAAAAA
P/wAAAAAAAA/+AAAAAAAAB/4AAAAAAAAH/gAAAAAAAAf+AAAAAAAAA/wAAAAAAAAD/AAAAAAAAAP
8AAAAAAAAA/wAAAAAAAAD/AAAAAAAAAH8AAAAAAAAAfwAAAAAAAAB/AAAAAAAAAH8AAAAAAAAAfw
AAAAAAAAB/AAAAAAAAAP8AAAAAAAAA/4AAAAAAAAD/AAAAAAAAAP4AAAAAAAAA/gAAAAAAAAH+AA
AAAAAAAf4AAAAAAAAB/gAAAAAAAAP+AAAAAAAAA/4AAAAAAAAH/gAAAAAAAAf+AAAAAAAAD/4AAA
AAAAAf/gAAAAAAAB/+AAAAAAAAP/4AAAAAAAB//gEAAAAAAP/+AYAAAAAB//8BwAAAAAP//4HwAA
AAD///wfgAAAAf///h/gAAAH////H/wAAB////+//4AA////////////////////////////////
//////////////8oAAAAMAAAAGAAAAABACAAAAAAAIAlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAgKlDA4CpQxeAqUMmgKlDJoCpQxqAqUMEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAACAqUMcgKlDZICpQ6aAqUPZgKlD+oCpQ/+AqUP/gKlD/4CpQ/+AqUP8gKlD3YCp
Q6uAqUNqgKlDIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAACAqUMCgKlDVYCpQ7yAqUP9gKlD/4CpQ/+AqUP/gKlD/4CpQ/+A
qUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/oCpQ8WAqUNggKlDBQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICpQ0+AqUPXgKlD/4CpQ/+AqUP/
gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+A
qUP/gKlD4ICpQ10AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAqUMWgKlD
sYCpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4mwUv+PtFv/kLVc/4qwU/+AqUP/
gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUPAgKlDHwAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAICpQz2AqUPlgKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/m7xs/8LWpf/i69T/+Pr1
///////////////////////5+/f/5e3Y/8bYqv+fvnL/gKlE/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/
gKlD7YCpQ0wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKlDVYCpQ/iAqUP/gKlD/4CpQ/+AqUP/gqpG/7LL
jf/r8eL/////////////////////////////////////////////////////////////////7vTn
/7fPlf+Eq0n/gKlD/4CpQ/+AqUP/gKlD/4CpQ/yAqUNoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAqUNTgKlD+4CpQ/+A
qUP/gKlD/4CpQ/+evXD/6vHh////////////////////////////////////////////////////
///////////////////////////////////v9ej/pMF5/4CpQ/+AqUP/gKlD/4CpQ/+AqUP+gKlD
ZwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAICpQzmAqUP3gKlD/4CpQ/+AqUP/gKlD/73Tn//9/vz/////////////////////////////
/////////////////////////////////////////////////////////////////////v7+/8fY
q/+BqkX/gKlD/4CpQ/+AqUP/gKlD/ICpQ0sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAgKlDE4CpQ+SAqUP/gKlD/4CpQ/+BqkX/0N+5////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////Y5cb/hKtJ/4CpQ/+AqUP/gKlD/4CpQ+6AqUMfAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKlDqICpQ/+AqUP/gKlD
/4CpQ//O3rf/////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////1+XG/4GqRf+A
qUP/gKlD/4CpQ/+AqUO+gKlDAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AACAqUNEgKlD/4CpQ/+AqUP/gKlD/7vRnP//////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////8fZq/+AqUP/gKlD/4CpQ/+AqUP/gKlDWgAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAqUPMgKlD/4CpQ/+AqUP/mrpp//39/P//////////////
////////////////////////////////////////////////////////////////////////////
//////////////////j4+P+pqan/vr6+//////////////////7+/v+jwXf/gKlD/4CpQ/+AqUP/
gKlD3oCpQwUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICpQ0WAqUP/gKlD/4CpQ/+A
qUP/5e3Y////////////////////////////////////////////////////////////////////
////////////////////////////////////////3t7e/3V1df9lZWX/6Ojo////////////////
///////t9OX/g6tH/4CpQ/+AqUP/gKlD/4CpQ1sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAICpQ62AqUP/gKlD/4CpQ/+nw33/////////////////////////////////////////////
//////////////////////////////////////////////////////////////++vr7/ZGRk/2Fh
Yf+srKz/////////////////////////////////ssuO/4CpQ/+AqUP/gKlD/4CpQ8MAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAgKlDDoCpQ/eAqUP/gKlD/4CpQ//i69P/////////////////
////////////////////////////////////////////////////////////////////////////
/////f39/6Kiov9hYWH/YWFh/319ff/7+/v/////////////////////////////////7PLj/4Cp
Q/+AqUP/gKlD/4CpQ/2AqUMeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKlDUICpQ/+AqUP/gKlD
/5G1Xf/+/v7/////////////////////////////////////////////////////////////////
///////////////////////////4+Pj/j4+P/2FhYf9hYWH/Z2dn/+Xl5f//////////////////
/////////////////////////5y8bv+AqUP/gKlD/4CpQ/+AqUNmAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAgKlDjYCpQ/+AqUP/gKlD/7jPlf//////////////////////////////////////////
/////////////////////////////////////////////////+/v7/+BgYH/YWFh/2FhYf9hYWH/
x8fH/////////////////////////////////////////////////8LWpv+AqUP/gKlD/4CpQ/+A
qUOjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKlDvYCpQ/+AqUP/gKlD/9Xjwf//////////////
////////////////////////////////////////////////////////////////////////6enp
/3Z2dv9hYWH/YWFh/2FhYf+oqKj/////////////////////////////////////////////////
/////+Hq0v+AqUP/gKlD/4CpQ/+AqUPTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKlD4ICpQ/+A
qUP/gKlD/+vx4v//////////////////////////////////////////////////////////////
///////////////////k5OT/cXFx/2FhYf9hYWH/YWFh/4uLi//9/f3/////////////////////
//////////////////////////////////f58v+AqUP/gKlD/4CpQ/+AqUP2AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAgKlD94CpQ/+AqUP/gKlD//r79///////////////////////////////////
/////////////////////////////////////////+Dg4P9vb2//YWFh/2FhYf9hYWH/eXl5//T0
9P////////////////////////////////////////////////////////////////+FrEv/gKlD
/4CpQ/+AqUP/gKlDDgAAAAAAAAAAAAAAAAAAAACdvG4DhKtJ+4atTP+GrUz/h69O////////////
/////////////////////////////////////////////////////////////////////4SEhP9h
YWH/YWFh/2FhYf9wcHD/6enp////////////////////////////////////////////////////
//////////////////+LslX/gKlD/4CpQ/+AqUP/gKlDGAAAAAAAAAAAAAAAAAAAAAAAAAAA8PXq
rf//////////////////////////////////////////////////////////////////////////
/////////////////////3Nzc/9hYWH/YWFh/25ubv/j4+P/////////////////////////////
//////////////////////////////////////////////+LsVT/gKlD/4CpQ/+AqUP/gKlDGAAA
AAAAAAAAAAAAAAAAAAAAAAAA+fv2oP//////////////////////////////////////////////
/////////////////////////////////////////////////3Z2dv9hYWH/YWFh/5GRkf//////
//////////////////////////////////////////////////////////////////////7+/v+D
q0j/gKlD/4CpQ/+AqUP/gKlDCwAAAAAAAAAAAAAAAAAAAAAAAAAA////hv//////////////////
////////////////////////////////////////////////////////////////////////////
/4CAgP9hYWH/YWFh/5iYmP//////////////////////////////////////////////////////
//////////////////////L37f+AqUP/gKlD/4CpQ/+AqUPwAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAA9/n0YP//////////////////////////////////////////////////////////////////
/////////////////////////////4uLi/9hYWH/YWFh/5+fn///////////////////////////
/////////////////////////////////////////////////9vny/+AqUP/gKlD/4CpQ/+AqUPL
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2OXGLf//////////////////////////////////////
/////////////////////////////////////////////////////////5iYmP9hYWH/YWFh/6io
qP//////////////////////////////////////////////////////////////////////////
/7zSnP+AqUP/gKlD/4CpQ/+AqUOZAAAAAAAAAAAAAAAAAAAAAAAAAACUt2EKgKlD8oatTP+GrUz/
hq1M/4atTP+GrUz/hq1M/4atTP+GrUz/hq1M/4atTP+LsVX/6/Hi////////////////////////
/////////6ampv9hYWH/YWFh/7Ozs///////////////////////////////////////////////
/////////////////////////v7+/5K2X/+AqUP/gKlD/4CpQ/+AqUNaAAAAAAAAAAAAAAAAAAAA
AAAAAACFrEsHgKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/
krZf//f58v///////////////////////////7e3t/9hYWH/YWFh/7+/v///////////////////
////////////////////////////////////////////////////4uvV/4CpQ/+AqUP/gKlD/4Cp
Q/mAqUMSAAAAAAAAAAAAAAAAAAAAAAAAAACAqUMHgKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD
/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/6PBd//9/vz//////////////////////8jIyP9hYWH/
YWFh/83Nzf//////////////////////////////////////////////////////////////////
////qMSA/4CpQ/+AqUP/gKlD/4CpQ7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAqUMHgKlD/4Cp
Q/+AqUP/gKlD/4CpQ/+AqUP/gqpH/4atTP+GrUz/hq1M/4GqRf+AqUP/gKlD/4CpQ/+4z5b/////
/////////////////9vb2/9hYWH/YWFh/97e3v//////////////////////////////////////
///////////////////////////h6tP/gKlD/4CpQ/+AqUP/gKlD/4CpQ0YAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAACAqUMHgKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/jrNZ//f59P//////////////
//////////////////////////////////////////////Dw8P9hYWH/YWFh/+/v7///////////
//////////////////////////////////////////////////v8+f+VuGP/gKlD/4CpQ/+AqUP/
gKlDygAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAqUMDgKlD/4CpQ/+AqUP/gKlD/4CpQ/+A
qUP/gKlD/6jEgP/+/v7///////////////////////////////////////////////////////7+
/v9sbGz/Z2dn//7+/v//////////////////////////////////////////////////////////
/7PMj/+AqUP/gKlD/4CpQ/+AqUP+gKlDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAqUMD
gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+50Jn/////////////////////////////
//////////////////////////////+Kior/goKC////////////////////////////////////
////////////////////////xNeo/4CpQ/+AqUP/gKlD/4CpQ/+AqUOfAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAACAqUMDgKlD/4CpQ/+AqUP/gKlD/4CpQ9CAqUP/gKlD/4CpQ/+AqUP/
udCY//7+/v////////////////////////////////////////////////+0tLT/qKio////////
///////////////////////////////////////////////D1qf/gKlD/4CpQ/+AqUP/gKlD/4Cp
Q9mAqUMNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAqUMDgKlD/4CpQ/+AqUP/gKlD
/4CpQyqAqUPmgKlD/4CpQ/+AqUP/gKlD/6fDff/2+fL/////////////////////////////////
///////////29vb/8PDw////////////////////////////////////////////+vv3/7DKiv+A
qUP/gKlD/4CpQ/+AqUP/gKlD74CpQy0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAgKlD/4CpQ/+AqUP/gKlD/4CpQwuAqUMvgKlD74CpQ/+AqUP/gKlD/4CpQ/+Nslf/1OLA
//7+/v//////////////////////////////////////////////////////////////////////
///////////a5sr/kbVd/4CpQ/+AqUP/gKlD/4CpQ/+AqUP2gKlDPwAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKlD/4CpQ/+AqUP/gKlD/4CpQwsAAAAAgKlDLoCp
Q+WAqUP/gKlD/4CpQ/+AqUP/gKlD/5m6Z//T4r7/+/z5////////////////////////////////
///////////////////////8/fv/1+XG/569cP+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ+6AqUM9
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKlDkICpQ/+A
qUP/gKlD/4CpQwcAAAAAAAAAAICpQx6AqUPHgKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/h69O/6vH
hP/L27P/4erS//D16f/4+vX/+fv2//H26//j69X/zd62/63JiP+KsVP/gKlD/4CpQ/+AqUP/gKlD
/4CpQ/+AqUP/gKlD04CpQykAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAICpQ2aAqUP5gKlD/4CpQwcAAAAAAAAAAAAAAACAqUMFgKlDhYCpQ/qA
qUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4Cp
Q/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/2AqUOUgKlDCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAqUNBgKlD7ICpQwcAAAAA
AAAAAAAAAAAAAAAAAAAAAICpQyiAqUOvgKlD/YCpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+A
qUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlDuoCpQzMAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAgKlDJICpQwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKlDKoCpQ46AqUPn
gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD/4CpQ/+AqUP/gKlD7YCpQ5aA
qUM0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAACAqUMDgKlDOoCpQ3mAqUOngKlDzYCpQ+SAqUPxgKlD84CpQ+aAqUPQ
gKlDqoCpQ36AqUNBgKlDBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////AAD///////8AAP//+B///wAA
//+AAf//AAD//AAAP/8AAP/4AAAf/wAA/+AAAAf/AAD/wAAAA/8AAP+AAAAB/wAA/wAAAAD/AAD+
AAAAAH8AAPwAAAAAPwAA/AAAAAAfAAD4AAAAAB8AAPgAAAAADwAA8AAAAAAPAADwAAAAAA8AAOAA
AAAABwAA4AAAAAAHAADgAAAAAAcAAOAAAAAABwAA4AAAAAAHAADgAAAAAAMAAMAAAAAAAwAA4AAA
AAADAADgAAAAAAMAAOAAAAAABwAA4AAAAAAHAADgAAAAAAcAAMAAAAAABwAAwAAAAAAHAADAAAAA
AA8AAMAAAAAADwAAwAAAAAAfAADAAAAAAB8AAMAAAAAAPwAAwAAAAAA/AADAAAAAAH8AAOAAAAAA
/wAA4IAAAAH/AADgwAAAA/8AAPDgAAAH/wAA+PgAAB//AAD8/gAAf/8AAP//gAH//wAA////////
AAD///////8AAP///////wAAKAAAACgAAABQAAAAAQAgAAAAAABAGgAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
ha1LLYWtS3aFrUuwha1L2YWtS/uFrUv/ha1L/4WtS/yFrUvgha1LtoWtS4GFrUs4AAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtSw6Dq0mPha1L+YWtS/+FrUv/ha1L
/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUuhha1LHwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAIWtS6GFrUv/g6tJ/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4Wt
S/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUu7ha1LDwAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
ha1LUIWtS/+FrUv/ha1L/4OrSf2FrUv/hK1K/4KrR/9/qUP/fqhA/3ynPv98pz3/fKY9/3ynPv99
qED/f6lD/4KrRv+ErEr/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUtvAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1LnYWtS/+FrUv/ha1L
/4WtS/+Dq0j9gKlD/3qlO/+cvG3/wtam/9znzP/w9On/+Pr2//n79//y9ez/3+rS/8farf+iwXf/
fKc+/3+pQv+DrEn/ha1L/4WtS/+FrUv/ha1L/4WtS74AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1LxIWtS/+FrUv/ha1L/4WtSv+AqkT/gapG/7/T
of/7/fv////////////////////////////////////////////////////////////J27H/h65P
/3+pQv+ErEr/ha1L/4WtS/+FrUv/ha1L5QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAha1LwYWtS/+FrUv/ha1L/4SsSv96pTz/r8mJ//////3/////////////////
//////////////////////////////////////////////////////////////++057/fKc9/4Os
Sf+FrUv/ha1L/4WtS/+FrUvlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1L
loWtS/+FrUv/ha1L/4OsSP9+qEH/3ejN///////+/v/9////////////////////////////////
/////////////////////////////////////////////////////+zy5P+FrUv/gqtH/4WtS/+F
rUv/ha1L/4WtS8QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1LRoWtS/+FrUv/ha1L/4Os
SP+Cq0j/8PXp/////////////f39/f//////////////////////////////////////////////
////////////////////////////////////////////+/z6/4yyV/+Cq0b/ha1L/4WtS/+FrUv/
ha1LdgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtS/+FrUv/ha1L/4SsSv9+qEH/8PXp////////
//////////39/f3/////////////////////////////////////////////////////////////
///////////////////////////////////9/fz/hq1M/4OsSP+FrUv/ha1L/4WtS/+FrUsSAAAA
AAAAAAAAAAAAAAAAAIWtS4+FrUv/ha1L/4WtS/96pjz/2ufJ///////////////////////9/f39
////////////////////////////////////////////////////////////////////////////
////zs7O//7+/v///////////+/z6P98pz7/hKxK/4WtS/+FrUv/ha1LvwAAAAAAAAAAAAAAAAAA
AACFrUv/ha1L/4WtS/+BqkX/qMR+/////////////////////////////f39/f//////////////
///////////////////////////////////////////////////////09PT/enp6/25ubv//////
////////////////wNSj/36oQf+FrUv/ha1L/4WtS/+FrUskAAAAAAAAAACDq0l8g6tJ/4OrSf2D
q0n9fahB//v8+v3//v/9/f39/f39/f39/f39/f39/f7+/v79/f39/f39/f39/f39/f39/f39/f39
/f39/f39/f39/f39/f39/f39/v7+/f////3Q0ND9X19f/VdXV/3g4OD9/////f39/f39/f39/v7+
/f////2JsFH9gqpH/YOrSf2Dq0n/g6tJqgAAAAAAAAAAha1L7IWtS/+FrUv/gKpE/7TMkf//////
///////////////////////////9/f39////////////////////////////////////////////
//////////////+vr6//WVlZ/2BgYP+fn5//////////////////////////////////zNy0/3+p
Qv+FrUv/ha1L/4WtS/8AAAAAha1LGIWtS/+FrUv/ha1L/3umPP/x9ez/////////////////////
/////////////f39/f////////////////////////////////////////////////////+Tk5P/
XV1d/2VlZf9xcXH///////////////////////////////////////////99p0D/hKxK/4WtS/+F
rUv/ha1LQoWtS2CFrUv/ha1L/4OsSP+Os1n///////////////////////////////////////39
/f3///////////////////////////////////////////////9/f3//YGBg/2dnZ/9eXl7/8fHx
////////////////////////////////////////////psN8/4GqRv+FrUv/ha1L/4WtS4qFrUuY
ha1L/4WtS/+AqkT/ts2T///////////////////////////////////////9/f39////////////
//////////////////////////z8/P9xcXH/Y2Nj/2hoaP9aWlr/0NDQ////////////////////
/////////////////////////////8rbsf9/qUL/ha1L/4WtS/+FrUvCha1LwIWtS/+FrUv/f6hC
/8/fuf///////////////////////////////////////f39/f//////////////////////////
//////f39/9ra2v/ZGRk/2hoaP9eXl7/rKys////////////////////////////////////////
///////////////l7dn/fac//4WtS/+FrUv/ha1L7IWtS9uFrUv/ha1L/32oQP/g69P/////////
//////////////////////////////39/f3///////////////////////////f39/9paWn/ZWVl
/2hoaP9hYWH/kZGR////////////////////////////////////////////////////////////
9/nz/3ynPf+FrUv/ha1L/4WtS/98pz7ueqY8/3qmPP9yoDD/6O7c////////////////////////
///////////////9/f39//////////////////////////+QkJD/YmJi/2hoaP9jY2P/f39/////
//////////////////////////////////////////////////////////////z9/f99qD//hKxK
/4WtS/+FrUv/8fXsjP//////////////////////////////////////////////////////////
/f39/f//////////////////////////g4OD/2VlZf9lZWX/eXl5////////////////////////
///////////////////////////////////////////////8/vv/fag//4SsSv+FrUv/ha1L//z9
/IP///////////////////////////////////////////////////////////39/f3/////////
/////////////////4mJif9kZGT/Y2Nj/5ycnP//////////////////////////////////////
////////////////////////////////9vjy/3ynPf+FrUv/ha1L/4WtS/////9n////////////
///////////////////////////////////////////////9/f39////////////////////////
//+UlJT/Y2Nj/2NjY/+hoaH/////////////////////////////////////////////////////
/////////////////+Ps1f99qED/ha1L/4WtS/+FrUvn/P37Of//////////////////////////
/////////////////////////////////f39/f//////////////////////////oKCg/2NjY/9i
YmL/qqqq////////////////////////////////////////////////////////////////////
///H2q3/f6lD/4WtS/+FrUv/ha1LvAAAAAD/////////////////////////////////////////
//////////////////7+/v3//////////////////////////6+vr/9iYmL/YWFh/7W1tf//////
////////////////////////////////////////////////////////////////ob91/4KrRv+F
rUv/ha1L/4WtS4R/qUL/e6Y8/3umPP97pjz/e6Y8/3umPP97pjz/e6Y8/3umPP97pjz/eKQ4/5u9
bf/////9//////////////////////////+/v7//YGBg/2BgYP/AwMD/////////////////////
/////////////////////////////////////////////////3umPf+ErEr/ha1L/4WtS/+FrUs5
ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/9/qUL/ob92/f//////
////////////////////0tLS/19fX/9fX1//0NDQ////////////////////////////////////
/////////////////////////////8bYqv9/qUL/ha1L/4WtS/+FrUv/AAAAAIWtS/+FrUv/ha1L
/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/3ymPv21zZL/////////////////
/////+bm5v9eXl7/Xl5e/97e3v//////////////////////////////////////////////////
//////////////+ErEr/hKxJ/4WtS/+FrUv/ha1LngAAAACFrUv/ha1L/4WtS/+FrUv/ha1L/4Wt
S/+FrUv/gapF/32nP/99pz//fac//32oP/98pj79dKIz/7PMkf/////////////////9/f3/XFxc
/1xcXP/z8/P///////////////////////////////////////////////////////////+3zpX/
f6lD/4WtS/+FrUv/ha1L/4WtSxcAAAAAha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/gapF/7fOlv/r
8eP/5e3Z/+Xt2f/l7dn/5e3Y/d/p0f/f6tH//////////////////////2hoaP9eXl7/////////
///////////////////////////////////////////////////j7Nf/eqY8/4SsSv+FrUv/ha1L
/4WtS68AAAAAAAAAAIWtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4SsSv99qEH/6fDf////////////
//////////3///////////////////////////////+Dg4P/bm5u////////////////////////
///////////////////////////////2+PP/gapF/4SsSf+FrUv/ha1L/4WtS/+FrUsGAAAAAAAA
AACFrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/hKxJ/36oQv/l7dn////////////9/f39////
////////////////////////////paWl/42Njf//////////////////////////////////////
///////////09+7/ha1M/4OrSP+FrUv/ha1L/4WtS/+FrUteAAAAAAAAAAAAAAAAha1L/4WtS/+F
rUv/ha1L/4WtS8SFrUv/ha1L/4WtS/+ErEn/e6Y8/8/duP////////7//f//////////////////
/////////////+fn5//U1NT////////////////////////////////////////////g6dH/gKlE
/4OrSP+FrUv/ha1L/4WtS/+FrUusAAAAAAAAAAAAAAAAAAAAAIWtS/+FrUv/ha1L/4WtS/+FrUs0
ha1LoIWtS/+FrUv/ha1L/4SsSv98pz3/oL90//j59P3/////////////////////////////////
//////////////////////////////////////////////+vyYn/e6U8/4SsSf+FrUv/ha1L/4Wt
S/+FrUvRAAAAAAAAAAAAAAAAAAAAAAAAAACFrUv/ha1L/4WtS/+FrUv/ha1LRwAAAACFrUunha1L
/4WtS/+FrUv/ha1L/4GqRv98pz/9sMqK/+zy5P//////////////////////////////////////
////////////////9fjw/7nQmv9/qUT/gKpE/4StSv+FrUv/ha1L/4WtS/+FrUvOAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAha1L/4WtS/+FrUv/ha1L/4WtS0gAAAAAAAAAAIWtS3+FrUv/ha1L/4Wt
S/+FrUv/g6tJ/YGqRf97pj3/jbJY/7TNkv/Q37r/4+zX/+3z5P/t8+b/5e3a/9TiwP+60Jn/lbdi
/3qmO/+AqkT/hKxK/4WtS/+FrUv/ha1L/4WtS/+FrUumAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAIWtSyOFrUv/ha1L/4WtS/+FrUtFAAAAAAAAAAAAAAAAha1LNIWtS/SFrUv/ha1L/4OrSf2F
rUv/ha1L/4OsSP+AqkT/fqhC/32oQP98pz//fKc+/32nP/9+qEH/gKpE/4OrSP+FrUv/ha1L/4Wt
S/+FrUv/ha1L/4WtS/+FrUtTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1L
D4WtS/2FrUv/hq5LRQAAAAAAAAAAAAAAAAAAAAAAAAAAha1LgIWtS/+Dq0n/ha1L/4WtS/+FrUv/
ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS5sA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFrUsLha1L/4au
S0kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAg6tJc4WtS+aFrUv/ha1L/4WtS/+FrUv/ha1L
/4WtS/+FrUv/ha1L/4WtS/+FrUv/ha1L/4WtS/+FrUvzha1Lh4WtSwQAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWtSxKGrkshAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAha1LEoWtS1yFrUuZha1Lw4WtS9+FrUvtha1L74Wt
S+KFrUvIha1LoYWtS2aFrUsdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAD//AA//wAAAP/gAAf/AAAA/8AAAf8AAAD/AAAA/wAAAP4AAAB/AAAA
/AAAAD8AAAD4AAAAHwAAAPAAAAAPAAAA4AAAAAcAAADgAAAAAwAAAMAAAAADAAAAwAAAAAEAAACA
AAAAAQAAAIAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAA
AAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAMAAAAAAAAAAwAAAAAAAAAHAAAAAAAAAA8AAAAAAAAA
HwAAAAQAAAA/AAAABgAAAH8AAAAHAAAA/wAAAIfAAAP/AAAAx/AAB/8AAADn/AA//wAAACgAAAAg
AAAAQAAAAAEAIAAAAAAAgBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAHynPTp8pz2DfKc9u3ynPd18pz3vfKc97nynPd58pz28fKc9
hXynPT0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAg7FBAn2pPZB8pz3/fKc9/3ynPf98pz3/fKc9/3ynPf98
pz3/fKc9/3ynPf98pz3/fKc9/3ynPf99qD2Ugq9ABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH2oPXd8pz3/fKc9/3ynPf96pjv/d6M2
/3SiMv9zoS//cqAu/3KgLv9zoC//dKIy/3ejNf96pjv/fKc9/3ynPf98pz3/fKc9fAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8pz3cfKc9/3ynPf96
pTr/c6Ew/3+oQv+0y5D/1+XE/+706P/8/Pz//Pz8/+/16f/Y5cf/tc6R/4CoRP9zoS//eqU6/3yn
Pf98pz3/fKc93YCsPwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACBrT8NfKc9
/XynPf97pjz/dKIy/4atTv/Z5cr/////////////////////////////////////////////////
/////9znzP+IrlD/dKEx/3umPP98pz3/fKc9/36qPhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAHynPf18pz3/e6Y8/3CfLP++05//////////////////////////////////////////
///////////////////////////////////C1aP/b58r/3umPP98pz3/fKc9/3+rPwMAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAB8pz3cfKc9/3umPP9yny//3+nR////////////////////////////
///////////////////////////////////////////////////////////j7NX/c6Aw/3umPP98
pz3/fKc94gAAAAAAAAAAAAAAAAAAAAAAAAAAfag9e3ynPf97pzz/cJ4s/9/p0f//////////////
////////////////////////////////////////////////////////////////////////////
///////i7Nb/cZ8u/3umPP98pz3/fKc9gwAAAAAAAAAAAAAAAIOxQQN8pz3/fKc9/3SiMv++05//
////////////////////////////////////////////////////////////////////////////
/////////+Dg4P/x8fH////////////C1aX/dKEx/3ynPf98pz3/ga5ACAAAAAAAAAAAfak+knyn
Pf96pTr/h65P////////////////////////////////////////////////////////////////
//////////////////////+dnZ3/SUlJ//////////////////////+JsFP/eqU5/3ynPf98pz2Z
AAAAAAAAAAB8pz3/fKc9/3OhMP/b58r/////////////////////////////////////////////
///////////////////////////////9/f3/b29v/0dHR//Kysr//////////////////////97o
0P9yoS//fKc9/3ynPf8AAAAAfKc9PHynPf96pjv/f6hD////////////////////////////////
////////////////////////////////////////////7Ozs/1tbW/9SUlL/iYmJ////////////
/////////////////////4KrR/96pjr/fKc9/3ynPUR8pz2GfKc9/3ejNv+zy47/////////////
/////////////////////////////////////////////////////////9nZ2f9QUFD/WFhY/2Fh
Yf//////////////////////////////////////ts+T/3ejNf98pz3/fKc9i3ynPbt8pz3/dKIy
/9fjxP/////////////////////////////////////////////////////////////////Ly8v/
TU1N/1tbW/9QUFD/7+/v///////////////////////////////////////a5sr/dKIx/3ynPf98
pz3AfKc93XynPf9zoS//7vTo////////////////////////////////////////////////////
////////wcHB/01NTf9cXFz/TExM/9LS0v//////////////////////////////////////////
//P27f9yoC//fKc9/3ynPeNyoC/ycaAt/2eZH//6+/j/////////////////////////////////
/////////////////////9PT0/9LS0v/XFxc/09PT/+2trb/////////////////////////////
///////////////////////+/3GgLv98pz3/fKc99PL266j////////////+////////////////
////////////////////////////////////////tLS0/1VVVf9WVlb/pqam////////////////
////////////////////////////////////////////caAu/3ynPf98pz30//7/lv//////////
//////////////////////////////////////////////////////////+7u7v/VVVV/1JSUv/g
4OD///////////////////////////////////////////////////////P27v9yoC//fKc9/3yn
PeP///90////////////////////////////////////////////////////////////////////
/8jIyP9UVFT/UlJS/+Tk5P//////////////////////////////////////////////////////
2ubL/3SiMf98pz3/fKc9weXt2S3/////////////////////////////////////////////////
////////////////////2dnZ/1NTU/9RUVH/7+/v////////////////////////////////////
//////////////////+2z5b/d6M1/3ynPf98pz2Mc6Ew/3SiM/90ojL/dKIy/3SiMv90ojL/dKIy
/3SiMv9unin/ydqx///////////////////////p6en/UlJS/1BQUP/9/f3/////////////////
/////////////////////////////////////4KsSP96pjr/fKc9/3ynPUV8pz3/e6Y8/3umPP97
pjz/e6Y8/3umPP97pjz/e6Y8/3umPP9unir/2eXI//////////////////39/f9PT0//UVFR////
///////////////////////////////////////////////////e6dH/cqAv/3ynPf98pz3/AAAA
AHynPf98pz3/fKc9/3ynPf98pz3/dqM0/3GfLP9xnyz/cZ8s/3CfLP9llx3/4+zV////////////
/////1NTU/9hYWH//////////////////////////////////////////////////////4yxVP95
pTn/fKc9/3ynPZsAAAAAfKc9/3ynPf98pz3/fKc9/3ajNP/L27L/////////////////////////
////////////////////////b29v/3R0dP//////////////////////////////////////////
///////E16j/c6Ex/3ynPf98pz3/gKw/CQAAAAB8pz3/fKc9/3ynPf98pz3/e6Y8/3CfK//g6tP/
//////////////////////////////////////////+NjY3/jo6O////////////////////////
////////////////////5O3X/3CfLf97pjz/fKc9/3ynPYUAAAAAAAAAAHynPf98pz3/fKc9/3yn
Pcx8pz3/e6Y8/3KgL//g6dH//////////////////////////////////////7a2tv+1tbX/////
/////////////////////////////////+Ls1v9yoDH/e6Y7/3ynPf98pz3jAAAAAAAAAAAAAAAA
fKc9/3ynPf98pz3/AAAAAHynPf58pz3/e6Y8/3CfLP++1KD/////////////////////////////
//////////7+/v/////////////////////////////////C1aX/cZ8u/3umO/98pz3/fKc9/36q
PgUAAAAAAAAAAAAAAAB8pz3/fKc9/3ynPf8AAAAAfag9DnynPf58pz3/e6Y8/3SiMf+HrlD/3ejN
///////////////////////////////////////////////////////e6dD/ibBT/3ShMf97pjz/
fKc9/3ynPf99qD0TAAAAAAAAAAAAAAAAAAAAAHynPep8pz3/fKc9/wAAAAAAAAAAf6w/AXynPd58
pz3/fKc9/3qlOv9zoS//gatF/7XNkv/Z5sn/8fbs//79/f/9/f3/8/bt/9rmyv+2z5P/gqxI/3Kg
L/96pTn/fKc9/3ynPf98pz3ifqo+BQAAAAAAAAAAAAAAAAAAAAAAAAAAfak+AXynPfZ8pz3/AAAA
AAAAAAAAAAAAAAAAAHynPX98pz3/fKc9/3ynPf96pjv/d6M1/3SiMf9yoC//cqAu/3KgLv9yoC//
dKIx/3ejNf96pjr/fKc9/3ynPf98pz3/fKc9hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAHynPfcAAAAAAAAAAAAAAAAAAAAAAAAAAIGuQAZ8pz2XfKc9/3ynPf98pz3/fKc9/3yn
Pf98pz3/fKc9/3ynPf98pz3/fKc9/3ynPf98pz3/fKc9mYCsPwgAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
fKc9QHynPYl8pz2+fKc94XynPfF8pz3yfKc94HynPb98pz2LfKc9QgAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+AH//8AAP/+AAB//AAAH/AAAA/wAAAH4AAAB8AA
AAOAAAABgAAAAYAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AQAAAAEAAAABAAAAAwAAAAcQAAAHEAAADxgAAB8eAAB/3wAA///gB/8oAAAAGAAAADAAAAABACAA
AAAAAGAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHekNyl3
pDeBd6Q3xXekN/J3pDf/d6Q3/3ekN/R3pDfJd6Q3hnekNy8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB2ozcld6Q3r3ajNft2ozX+d6Q3/3ajNf53pDf/dqM1
/najNf52ozX+d6Q3/3ajN/x2oze3d6Q3LAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAHajNWF2ozfzd6Q3/3ajNf52ozX+d6Q4/4qwUv6Zumn/mrpp/ouxVf54pDj+d6Q3/3ajNf52
ozX+d6Q39najNW4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAd6Q3eHekN/53pDf/d6Q3/4iv
T//E16f/8/bt///////////////////////19+//x9mt/4uxVP93pDf/d6Q3/3ekN/53pDeHAAAA
AAAAAAAAAAAAAAAAAAAAAAB2ozdad6Q3/XajNf53pDf+scqL//j79f7+/v7+//////7+/v7/////
/v7+/v7+/v7+/v7+//////n89/63zpT+d6Q4/3ajNf52ozf+d6Q3awAAAAAAAAAAAAAAAHajNR52
ozXwd6Q3/3ekN/7A1aH+/v7+//7+/v7+/v7+//////7+/v7//////v7+/v7+/v7+/v7+//////7+
/v7+/v7+x9mu/3ekOP52ozX+d6Q39najNSsAAAAAAAAAAHekN6V3pDf/d6Q3/63Hhv/+/v7/////
/////////////////////////////////////////////v7+/9XV1f/Z2dn////+/7bNk/93pDf/
d6Q3/3ekN7UAAAAAd6Q3H3ajNfl2ozX+ha1J//b48v7+/v7+//////7+/v7+/v7+//////7+/v7/
/////v7+/v7+/v78/Pz+p6en/2lpaf7y8vL+//////n79v6JsFL+d6Q3/3ajNfx2ozUsd6Q3cXaj
Nf52ozX+vNKd//7+/v7+/v7+//////7+/v7+/v7+//////7+/v7//////v7+/vf39/6Li4v+WFhY
/8jIyP7+/v7+//////7+/v7F2Kn+d6Q3/3ajNf52ozWCd6Q3snekN/93pDf/6vHh////////////
////////////////////////////////7u7u/3l5ef9XV1f/oaGh///////////////////////z
9u3/d6Q3/3ekN/93pDfDd6Q323ajNf6AqUP+/v7+//7+/v7+/v7+//////7+/v7+/v7+//////7+
/v7r6+v/cHBw/lZWVv6Dg4P+/Pz8//7+/v7+/v7+//////7+/v7+/v7+iK9Q/3ajNf52ozXseqY8
7nynPf+RtF7///////////////////////////////////////n5+f9vb2//V1dX/3Nzc//y8vL/
////////////////////////////////lbhk/3ekN/93pDf+9fjvv/7+/v7+/v7+//////7+/v7+
/v7+//////7+/v7+/v7+//////Hx8f5aWlr/W1tb/urq6v7+/v7+//////7+/v7+/v7+//////7+
/v7+/v7+lLhi/3ajNf52ozX9+fz3qP7+/v7+/v7+//////7+/v7+/v7+//////7+/v7+/v7+////
//b29v5cXFz/YWFh/v7+/v7+/v7+//////7+/v7+/v7+//////7+/v7+/v7+ha1L/3ajNf52ozXn
1eLCkerx4P7q8eD+6vHh/+rx4P7q8eD+7vTn//7+/v7+/v7+//////39/f5iYmL/aWlp/v7+/v7+
/v7+//////7+/v7+/v7+//////7+/v7t8+T+d6Q3/3ajNf52ozW7d6Q39nekN/93pDf/d6Q3/3ek
N/93pDf/eaU6/9nlxv////////////////9wcHD/dXV1////////////////////////////////
//////+90p7/d6Q3/3ekN/93pDd3d6Q39HajNf52ozX+d6Q3/3ajNf52ozX+d6Q3/4GqRf7q8eD+
//////7+/v6Dg4P/hYWF/v7+/v7+/v7+//////7+/v7+/v7+//////X47/6Dq0j+d6Q3/3ajNfl2
ozUhd6Q383ajNf52ozX+d6Q3/5e5Zv7v9Oj+8fXr//H16v73+fX+//////7+/v6ampr/l5eX/v7+
/v7+/v7+//////7+/v7+/v7+/v7+/6jEf/52ozX+d6Q3/3ajNaMAAAAAd6Q383ekN/93pDf9d6Q3
/3ekN/+vyIn//f79//////////////////////+5ubn/srKy///////////////////////+/v3/
t86U/3ekN/93pDf/d6Q37XekNx0AAAAAd6Q383ajNf52ozWed6Q3+XajNf52ozX+n75y/+/06P7+
/v7+//////7+/v7s7Oz/5+fn/v7+/v7+/v7+//////L27P6lwnr+d6Q3/3ajNf52ozX7d6Q3UgAA
AAAAAAAAd6Q38XajNf52ozVbd6Q3WXajNfl2ozX+d6Q3/36oQf6xy4z+4evU//z9+/7//////v7+
/v39/P7k7Nf+tM2R/4CpQ/52ozX+d6Q3/3ajNft2ozVnAAAAAAAAAAAAAAAAd6Q3iXekN/13pDdZ
AAAAAHekN0F3pDfjd6Q3/3ekN/93pDf/d6Q3/3mlO/+Hrk7/h69P/3qmPP93pDf/d6Q3/3ekN/93
pDf/d6Q36XekN0wAAAAAAAAAAAAAAAAAAAAAAAAAAHajNWJ2ozVQAAAAAAAAAAB2ozURd6Q3jXaj
NfF2ozX+d6Q3/3ajNf53pDf/dqM1/najNf52ozX+d6Q3/3ajNfR2ozWVd6Q3FgAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAB2ozUCAAAAAAAAAAAAAAAAAAAAAHajNRF2ozVfd6Q3onajNc13pDfj
dqM15HajNc92ozWld6Q3Y3ajNRUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gB/APgAHwDw
AA8A4AAHAMAAAwCAAAEAgAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAEAAAABAAAAAwAAAAcAEAAPAJgAHwDeAH8AKAAAABQAAAAoAAAAAQAgAAAAAACQBgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHikOFZ4pDiveKQ47HikOP94pDj/
eKQ47nikOLR4pDhcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHejOFJ2
ojj/dqI3/3OgM/9xny7/bp4s/26eLP9vni7/daIz/3aiNv92ojj/dqI2XQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAB3ozihd6M2/3ShM/9unSn/nLxr/8fYrf/c58v/3efN/8jbsP+evW//b54q
/XOgMv93ozf/d6M3rwAAAAAAAAAAAAAAAAAAAAAAAAAAd6M4mnejNv9vniz9kbVf//b48v//////
///////////////////////////4+/f9l7lm/m6eK/53ozb/d6M4rQAAAAAAAAAAAAAAAHejNkh3
ozb/b54s/aTBe/7////9/////f39/f39/f39/f39/f39/f39/f39/f39/f////3////9rciH/W6e
K/13ozb/d6M2WwAAAAAAAAAAdqI4+HShNP+Os1n//////f//////////////////////////////
////////////3t7e/8PDw///////lbhk/3OgM/93ozj/AAAAAHikOEl2ojf/bZ0o//H06v/////9
/////////////////////////////////////7e3t/9ISEj//Pz8///////3+fT/bp0p/3aiN/93
ozZYeKQ4oHShNP+TtmD///////39/f3///////////////////////////////+ZmZn/Ozs7/9bW
1v////////////////+cvGz/c6Az/3ejNrB3ozfYcZ8v/77Sn////////f39/f//////////////
////////////g4OD/0JCQv+srKz//////////////////////8bYrP9xny7/d6M25nGfLfJqmyP/
zt63///////9/f39/////////////////////4aGhv9ISEj/iYmJ////////////////////////
////2ebI/2+eLP93ozb+////wv////////////////39/f3/////////////////////W1tb/2Nj
Y//////////////////////////////////X5cb/b54t/3ejNv3+/v2h////////////////////
/f////////////////////9nZ2f/dHR0/////////////////////////////////8LVpv9xny//
d6M24Zu8a8qow3//p8N+/6fDfv+mwnz9ssqO/////////////////3Z2dv9+fn7/////////////
////////////////////lLdi/3WiNP92ojandaIz+HOgMf5zoDH9cp8v/WqbJP1jlhz/rciI////
////////ioqK/4uLi/////////////39/f39/f39/////fD16f1tnCj9dqI2/3ejN0x4pDj0dqI2
/naiNf5+qEH+6vHg/eLr1v/c58v//v7+//////+ioqL/n5+f/////////////f39/f7+/v7////+
irBU/nShM/93ozf3AAAAAHikOPR2ojb9d6M2/3OgMf6XuWj9/////////////////////8HBwf+7
u7v////////////////9/////py8bf5xny3+d6M3/3ejN0QAAAAAeKQ493aiNvl3ozhtd6M2/3Kf
L/6ErEn/5e3Z//////////////7///38/////////////+rx4P2Irk7+cZ8u/nejN/93ozeNAAAA
AAAAAAB4pDjrdqI2/wAAAAB3ozh5d6M2/3WhNf9tnSn/iLBR/7bNk//L3LP/y9y0/7fOlv+LsVX/
bZ0o/XShM/93ozf/d6M3iAAAAAAAAAAAAAAAAHikOAR2ojblAAAAAAAAAAB3ozYwd6M45naiOP91
oTX/cp8x/2+eLv9vni7/cp8x/3aiNf92ojb/d6M37XejNzoAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAd6M2NXejNpB3ozbKd6M25nejNud3ozbMdqI2lXejNzsAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAD8A/AA8ADwAOAAcADAADAAgAAQAIAAEAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAwACAAcAAwAPAA/APwACgAAAAQAAAAIAAAAAEAIAAA
AAAAQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdqM1IHajNZd1ojTgdKIx/3Si
Mf91ojTkdqM1m3ajNSYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdqM1p3SiM/9unSr/bZ0n
/4OsSf+FrEr/bZ0o/26dKP90ojH/dqM1sAAAAAAAAAAAAAAAAAAAAAAAAAAAdqM11nGgLv96pTr/
0eG8///////////////////////T4sD/faY//3CgLf92ozXfAAAAAAAAAAAAAAAAdqM1nnGgLv+L
sFX///////////////////////////////////////////+RtVz/cKAu/3ajNa8AAAAAdqM1GHSi
M/93ozf//////////////////////////////////////+fn5/+4uLn//////3ymPv90ojP/dqM1
I3ajNY1unSr/y9y0/////////////////////////////////8zMzP9FRUX//Pz8///////S4b7/
bp0q/3ajNZl1ojTSapok/////////////////////////////////7a2tv82Njb/3t7e////////
/////////2ybJv91ojTebJwm9XShMf///////////////////////////7Ozs/84ODj/vLy8////
//////////////////+Aqkf/dKIx/v///8z///////////////////////////////93d3f/goKC
////////////////////////////gKlD/3SiM/zt8+Or+fv5//n7+P/4+/f/////////////////
iIiI/5GRkf///////////////////////////2ucJf91ojTZbJwm/GubJf9rmyX/ZZgd/1qQC//7
/Pn//////5mZmf+bm5v//////////////////////8vctP9unSr/dqM1kHajNfZ2ozX/cJ4s/8fZ
rP/K27H/3OfL//////+vr6//rq6u//////////////////////92ozT/daIz/3ajNRd2ozX2dqM1
+HShMf+Hrk//////////////////1NTU/8zMzP////////////////+Grkz/caAv/3ajNZoAAAAA
dqM1/3ajNYN2ozWzc6Ew/3GhL//C1aT//P37/////////////f7+/8XYqv90ojH/c6Ev/3ajNckA
AAAAAAAAAHajNf92ozWbAAAAAHajNYh1ojP/b54r/2ubJP90ojP/dqI1/2ubJP9vniv/daIz/3aj
NZEAAAAAAAAAAAAAAAAAAAAAd6Q1EAAAAAAAAAAAdqM1CnajNX12ozXGdaI06XWiNOt2ozXIdqM1
gnajNQ0AAAAAAAAAAAAAAAAAAAAA8A8AAOAHAADAAwAAgAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAEAAAADAAAgBwAAsA8AAA==')
	#endregion
	$formEQSwitch.MainMenuStrip = $menustrip1
	$formEQSwitch.MaximizeBox = $False
	$formEQSwitch.MinimumSize = '100, 250'
	$formEQSwitch.Name = 'formEQSwitch'
	$formEQSwitch.ShowIcon = $False
	$formEQSwitch.StartPosition = 'Manual'
	$formEQSwitch.Text = 'EQSwitch'
	$formEQSwitch.add_Load($formEQSwitch_Load)
	$formEQSwitch.add_Move($formEQSwitch_Move)
	$formEQSwitch.add_Resize($formEQSwitch_Resize)
	#
	# labelRunningEQInstances
	#
	$labelRunningEQInstances.AutoSize = $True
	$labelRunningEQInstances.Location = '4, 53'
	$labelRunningEQInstances.Name = 'labelRunningEQInstances'
	$labelRunningEQInstances.Size = '0, 16'
	$labelRunningEQInstances.TabIndex = 30
	$labelRunningEQInstances.UseCompatibleTextRendering = $True
	#
	# listview1
	#
	$listview1.Activation = 'OneClick'
	$listview1.Anchor = 'Top, Bottom, Left, Right'
	$listview1.BackColor = 'Info'
	$listview1.Font = 'Microsoft Sans Serif, 9pt'
	$listview1.HotTracking = $True
	$listview1.HoverSelection = $True
	$listview1.Location = '4, 102'
	$listview1.MultiSelect = $False
	$listview1.Name = 'listview1'
	$listview1.Size = '137, 573'
	$listview1.TabIndex = 29
	$listview1.UseCompatibleStateImageBehavior = $False
	$listview1.View = 'List'
	$listview1.add_Click($listview1_Click)
	#
	# textbox1
	#
	$textbox1.Anchor = 'Top, Bottom, Left, Right'
	$textbox1.AutoCompleteMode = 'Append'
	$textbox1.AutoCompleteSource = 'CustomSource'
	$textbox1.BackColor = 'Info'
	$textbox1.Location = '4, 76'
	$textbox1.Name = 'textbox1'
	$textbox1.Size = '137, 20'
	$textbox1.TabIndex = 28
	$textbox1.add_Click($textbox1_Click)
	$textbox1.add_KeyDown($textbox1_KeyDown)
	#
	# buttonRefresh
	#
	$buttonRefresh.Anchor = 'Top, Left, Right'
	$buttonRefresh.BackgroundImageLayout = 'None'
	$buttonRefresh.Location = '4, 25'
	$buttonRefresh.Name = 'buttonRefresh'
	$buttonRefresh.Size = '137, 25'
	$buttonRefresh.TabIndex = 27
	$buttonRefresh.Text = 'Refresh'
	$buttonRefresh.UseCompatibleTextRendering = $True
	$buttonRefresh.UseVisualStyleBackColor = $True
	$buttonRefresh.add_Click($buttonRefresh_Click)
	#
	# menustrip1
	#
	[void]$menustrip1.Items.Add($toolsToolStripMenuItem)
	[void]$menustrip1.Items.Add($toolstripmenuitem1)
	$menustrip1.Location = '0, 0'
	$menustrip1.Name = 'menustrip1'
	$menustrip1.Size = '145, 24'
	$menustrip1.TabIndex = 31
	$menustrip1.Text = 'menustrip1'
	#
	# toolsToolStripMenuItem
	#
	[void]$toolsToolStripMenuItem.DropDownItems.Add($sortToolStripMenuItem)
	[void]$toolsToolStripMenuItem.DropDownItems.Add($fontSizeToolStripMenuItem)
	[void]$toolsToolStripMenuItem.DropDownItems.Add($resetToolStripMenuItem)
	$toolsToolStripMenuItem.Name = 'toolsToolStripMenuItem'
	$toolsToolStripMenuItem.Size = '47, 20'
	$toolsToolStripMenuItem.Text = 'Tools'
	#
	# sortToolStripMenuItem
	#
	[void]$sortToolStripMenuItem.DropDownItems.Add($AscendingToolStripMenuItem)
	[void]$sortToolStripMenuItem.DropDownItems.Add($DescendingToolStripMenuItem)
	[void]$sortToolStripMenuItem.DropDownItems.Add($NoneToolStripMenuItem)
	$sortToolStripMenuItem.Name = 'sortToolStripMenuItem'
	$sortToolStripMenuItem.Size = '152, 22'
	$sortToolStripMenuItem.Text = 'Sort'
	#
	# AscendingToolStripMenuItem
	#
	$AscendingToolStripMenuItem.Name = 'AscendingToolStripMenuItem'
	$AscendingToolStripMenuItem.Size = '152, 22'
	$AscendingToolStripMenuItem.Text = 'Ascending'
	$AscendingToolStripMenuItem.add_Click($AscendingToolStripMenuItem_Click)
	#
	# DescendingToolStripMenuItem
	#
	$DescendingToolStripMenuItem.Name = 'DescendingToolStripMenuItem'
	$DescendingToolStripMenuItem.Size = '152, 22'
	$DescendingToolStripMenuItem.Text = 'Descending'
	$DescendingToolStripMenuItem.add_Click($DescendingToolStripMenuItem_Click)
	#
	# NoneToolStripMenuItem
	#
	$NoneToolStripMenuItem.Name = 'NoneToolStripMenuItem'
	$NoneToolStripMenuItem.Size = '152, 22'
	$NoneToolStripMenuItem.Text = 'None'
	$NoneToolStripMenuItem.add_Click($NoneToolStripMenuItem_Click)
	#
	# resetToolStripMenuItem
	#
	$resetToolStripMenuItem.Name = 'resetToolStripMenuItem'
	$resetToolStripMenuItem.Size = '152, 22'
	$resetToolStripMenuItem.Text = 'Reset'
	$resetToolStripMenuItem.add_Click($resetToolStripMenuItem_Click)
	#
	# fontSizeToolStripMenuItem
	#
	[void]$fontSizeToolStripMenuItem.DropDownItems.Add($smallToolStripMenuItem)
	[void]$fontSizeToolStripMenuItem.DropDownItems.Add($mediumToolStripMenuItem)
	[void]$fontSizeToolStripMenuItem.DropDownItems.Add($largeToolStripMenuItem)
	[void]$fontSizeToolStripMenuItem.DropDownItems.Add($extraLargeToolStripMenuItem)
	$fontSizeToolStripMenuItem.Name = 'fontSizeToolStripMenuItem'
	$fontSizeToolStripMenuItem.Size = '152, 22'
	$fontSizeToolStripMenuItem.Text = 'Font Size'
	#
	# smallToolStripMenuItem
	#
	$smallToolStripMenuItem.Name = 'smallToolStripMenuItem'
	$smallToolStripMenuItem.Size = '133, 22'
	$smallToolStripMenuItem.Text = 'Small'
	$smallToolStripMenuItem.add_Click($smallToolStripMenuItem_Click)
	#
	# mediumToolStripMenuItem
	#
	$mediumToolStripMenuItem.Name = 'mediumToolStripMenuItem'
	$mediumToolStripMenuItem.Size = '133, 22'
	$mediumToolStripMenuItem.Text = 'Medium'
	$mediumToolStripMenuItem.add_Click($mediumToolStripMenuItem_Click)
	#
	# largeToolStripMenuItem
	#
	$largeToolStripMenuItem.Name = 'largeToolStripMenuItem'
	$largeToolStripMenuItem.Size = '133, 22'
	$largeToolStripMenuItem.Text = 'Large'
	$largeToolStripMenuItem.add_Click($largeToolStripMenuItem_Click)
	#
	# extraLargeToolStripMenuItem
	#
	$extraLargeToolStripMenuItem.Name = 'extraLargeToolStripMenuItem'
	$extraLargeToolStripMenuItem.Size = '133, 22'
	$extraLargeToolStripMenuItem.Text = 'Extra-Large'
	$extraLargeToolStripMenuItem.add_Click($extraLargeToolStripMenuItem_Click)
	#
	# toolstripmenuitem1
	#
	[void]$toolstripmenuitem1.DropDownItems.Add($aboutToolStripMenuItem)
	[void]$toolstripmenuitem1.DropDownItems.Add($sourceLinkToolStripMenuItem)
	$toolstripmenuitem1.Name = 'toolstripmenuitem1'
	$toolstripmenuitem1.Size = '44, 20'
	$toolstripmenuitem1.Text = 'Help'
	#
	# aboutToolStripMenuItem
	#
	$aboutToolStripMenuItem.Name = 'aboutToolStripMenuItem'
	$aboutToolStripMenuItem.Size = '152, 22'
	$aboutToolStripMenuItem.Text = 'About'
	$aboutToolStripMenuItem.add_Click($aboutToolStripMenuItem_Click)
	#
	# sourceLinkToolStripMenuItem
	#
	$sourceLinkToolStripMenuItem.Name = 'sourceLinkToolStripMenuItem'
	$sourceLinkToolStripMenuItem.Size = '152, 22'
	$sourceLinkToolStripMenuItem.Text = 'Source Link'
	$sourceLinkToolStripMenuItem.add_Click($sourceLinkToolStripMenuItem_Click)
	$menustrip1.ResumeLayout()
	$formEQSwitch.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formEQSwitch.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formEQSwitch.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formEQSwitch.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formEQSwitch.ShowDialog()

} #End Function

#Call the form
Show-QuickSwitch_psf | Out-Null
