<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2018 v5.5.155
     Generated on:       11/29/2018 7:17 AM
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2018
#>



#region Source: Startup.pss
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
		
	#--------------------------------------------------------------------------
	#TODO: Add initialization script here (Load modules and check requirements)
	
	
	#--------------------------------------------------------------------------
	
	if((Show-MainForm_psf) -eq 'OK')
	{
		
	}
	
	$script:ExitCode = 0 #Set the exit code for the Packager
}



#endregion Source: Startup.pss

#region Source: MainForm.psf
function Show-MainForm_psf
{
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$MainForm = New-Object 'System.Windows.Forms.Form'
	$buttonSaveAsDefaultLocatio = New-Object 'System.Windows.Forms.Button'
	$buttonBrowseFolder = New-Object 'System.Windows.Forms.Button'
	$ShortcutsFolder = New-Object 'System.Windows.Forms.TextBox'
	$labelShortcutsLocation = New-Object 'System.Windows.Forms.Label'
	$buttonBuildSampleTOONSCSV = New-Object 'System.Windows.Forms.Button'
	$labelPEQConfigurator = New-Object 'System.Windows.Forms.Label'
	$richtextbox1 = New-Object 'System.Windows.Forms.RichTextBox'
	$buttonBuildMQ2AutoLogin = New-Object 'System.Windows.Forms.Button'
	$buttonBuildAutoHotKey = New-Object 'System.Windows.Forms.Button'
	$buttonBuildShortcuts = New-Object 'System.Windows.Forms.Button'
	$labelToonsCsvLocation = New-Object 'System.Windows.Forms.Label'
	$buttonBrowse = New-Object 'System.Windows.Forms.Button'
	$toonsFile = New-Object 'System.Windows.Forms.TextBox'
	$menustrip1 = New-Object 'System.Windows.Forms.MenuStrip'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$tabcontrol1 = New-Object 'System.Windows.Forms.TabControl'
	$tabpage1 = New-Object 'System.Windows.Forms.TabPage'
	$buttonEQCPUAffinity = New-Object 'System.Windows.Forms.Button'
	$buttonKillAllEQWindows = New-Object 'System.Windows.Forms.Button'
	$buttonstartMissingToons = New-Object 'System.Windows.Forms.Button'
	$tabpage2 = New-Object 'System.Windows.Forms.TabPage'
	$combobox1 = New-Object 'System.Windows.Forms.ComboBox'
	$buttonTaskbarGroupingFix = New-Object 'System.Windows.Forms.Button'
	$buttonEQClientiniReadOnly = New-Object 'System.Windows.Forms.Button'
	$CPU = New-Object 'System.Windows.Forms.GroupBox'
	$labelLogicalProcessors = New-Object 'System.Windows.Forms.Label'
	$labelCores = New-Object 'System.Windows.Forms.Label'
	$labelCPUName = New-Object 'System.Windows.Forms.Label'
	$folderbrowserdialog1 = New-Object 'System.Windows.Forms.FolderBrowserDialog'
	$openfiledialog1 = New-Object 'System.Windows.Forms.OpenFileDialog'
	$openfiledialog2 = New-Object 'System.Windows.Forms.OpenFileDialog'
	$openfiledialog3 = New-Object 'System.Windows.Forms.OpenFileDialog'
	$openfiledialog4 = New-Object 'System.Windows.Forms.OpenFileDialog'
	$tooltip1 = New-Object 'System.Windows.Forms.ToolTip'
	$folderbrowserdialog2 = New-Object 'System.Windows.Forms.FolderBrowserDialog'
	$folderbrowserdialog3 = New-Object 'System.Windows.Forms.FolderBrowserDialog'
	$savefiledialog1 = New-Object 'System.Windows.Forms.SaveFileDialog'
	$folderbrowserdialog4 = New-Object 'System.Windows.Forms.FolderBrowserDialog'
	$helpToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$aboutToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$MainForm_Load = {
		#Disable buttons
		$buttonBuildShortcuts.Enabled = $false
		$buttonBuildAutoHotKey.Enabled = $false
		$buttonBuildMQ2AutoLogin.Enabled = $false
		$buttonstartMissingToons.Enabled = $false
		$buttonEQClientiniReadOnly.Enabled = $false
		if (Test-Path ".\PEQConfig.ini")
		{
			$INIcontent = Get-IniContent -filePath .\PEQConfig.ini
			$toonsFile.Text = $INIcontent.Paths.ToonsLocation
			$ShortcutsFolder.Text = $INIcontent.Paths.ShortcutsLocation
		}
		$cores = Get-WmiObject –class Win32_processor | Select-Object systemname, Name, DeviceID, NumberOfCores, NumberOfLogicalProcessors
		$labelCPUName.Text = "CPU: $($cores.Name)"
		$labelCores.Text = "Cores: $($cores.NumberOfCores)"
		$labelLogicalProcessors.Text = "Logical Processors: $($cores.NumberOfLogicalProcessors)"
	}
	
	$buttonCallChildForm_Click = {
		#TODO: Place custom script here
		if ((Show-ChildForm_psf) -eq 'OK')
		{
			
		}
	}
	
	$buttonBrowse_Click = {
		$openfiledialog1.Title = "Open Toons.CSV"
		#$openfiledialog1.InitialDirectory = $share
		#$openfiledialog1.DefaultExt = "CSV"
		$openfiledialog1.Filter = "CSV (*.csv)|*.CSV|All files (*.*)|*.*"
		if ($openfiledialog1.ShowDialog() -eq 'OK')
		{
			
			$toonsFile.Text = $openfiledialog1.FileName
			
		}
	}
	
	$toonsFile_TextChanged = {
		button-check
	}
	
	$buttonBuildShortcuts_Click = {
		buttondown
		$richtextbox1.Clear()
		$ini = @()
		$toons = Import-Csv -Path $toonsFile.Text #Toons CSV location
		foreach ($toon in $toons)
		{
			if ($toon.Login -ne '')
			{
				$ini += [pscustomobject]@{
					Login = $toon.Login.Trim()
					Password = $toon.Password.Trim()
					Server = $toon.Server.Trim()
					Character = $toon.Character.Trim()
					EQPath = $toon.EQPath.Trim()
				}
			}
		}
		
		if (-not ($ShortcutsFolder.Text.EndsWith('\')))
		{
			$ShortcutsFolder.Text = $shortcutsFolder.Text + '\'
		}
		
		Update-Display "Building Shortcuts..." -color 'Orange'
		foreach ($i in $ini)
		{
			$TargetPathExe = $i.EQPath + '\eqgame.exe'
			$Arguments = "patchme /login:$($i.Login)"
			$ShortcutName = $i.Character + '.lnk'
			$WorkingDirectory = $i.EQPath
			#$Description = ''
			
			#$FullLink = $ShortcutsPath + $Shortcut
			$Shell = New-Object -ComObject ("WScript.Shell")
			$ShortCut = $Shell.CreateShortcut($ShortcutsFolder.Text + $ShortcutName)
			$ShortCut.TargetPath = $TargetPathExe #"yourexecutable.exe"
			$ShortCut.Arguments = $Arguments #$Arguments #"-arguementsifrequired"
			$ShortCut.WorkingDirectory = $WorkingDirectory #"c:\your\executable\folder\path";
			#$ShortCut.WindowStyle = 1;
			#$ShortCut.Hotkey = "CTRL+SHIFT+F";
			#$ShortCut.IconLocation = "yourexecutable.exe, 0";
			#$ShortCut.Description = $Description #"Your Custom Shortcut Description";
			$ShortCut.Save()
		}
		Update-Display "Finished Building Shortcuts!" -color 'Green'
		Update-Display "Shortcuts saved to:" -color 'Orange'
		Update-Display "File:///$($ShortcutsFolder.Text)"
		$buttonBuildAutoHotKey.Enabled = $true
		
		buttonup
		
	}
	
	$buttonBuildAutoHotKey_Click = {
		buttondown
		$richtextbox1.Clear()
		$shortcuts = Get-ChildItem -Path $shortcutsFolder.Text -filter "*.lnk" #New shortcuts folder
		$toons = Import-Csv -Path $toonsFile.Text #Toons CSV location
		$ini = @()
		foreach ($toon in $toons)
		{
			if ($toon.Login -ne '')
			{
				$ini += [pscustomobject]@{
					Login = $toon.Login.Trim()
					Password = $toon.Password.Trim()
					Server = $toon.Server.Trim()
					Character = $toon.Character.Trim()
					EQPath = $toon.EQPath.Trim()
				}
			}
		}
		$lines = @()
		if ($shortcuts) #only run if $shortcuts contains data
		{
			$richtextbox1.Clear()
			#reorder to match toons spreadsheet order
			foreach ($i in $ini)
			{
				foreach ($s in $shortcuts)
				{
					if ($s.BaseName -eq $i.Character)
					{
						$lines += [PSCustomObject] @{
							FullName = $s.FullName
							Name	 = $s.BaseName
						}
					}
				}
			}
			Clear-Host
			#Build AutoHotKey
			Update-Display '----Copy/Paste lines below into AutoHotKey script----' -color 'Orange'
			$list = @()
			$list += '#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.'
			$list += '#Warn  ; Recommended for catching common errors.'
			$list += 'SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.'
			$list += 'SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.'
			$list += ''
			foreach ($l in $lines)
			{
				$list += 'Run ' + $($l.FullName)
				$list += 'WinWaitActive, EverQuest'
				$list += 'WinSetTitle, ' + $($l.Name)
				$list += ''
			}
			Update-Display $list
			Update-Display '----Copy/Paste lines above into AutoHotKey script----' -color 'Orange'
		}
		else
		{
			Update-Display "Shortcuts folder is empty or not found.  Please create EQ shortcuts and try again." -color 'Yellow'
		}
		
		buttonup
	}
	
	$buttonBuildMQ2AutoLogin_Click = {
		buttondown
		$richtextbox1.Clear()
		$toons = Import-Csv -Path $toonsFile.Text #Toons CSV location
		$ini = @()
		foreach ($toon in $toons)
		{
			if ($toon.Login -ne '')
			{
				$ini += [pscustomobject]@{
					Login = '[' + $toon.Login.Trim() + ']'
					Password = 'Password=' + $toon.Password.Trim()
					Server = 'Server=' + $toon.Server.Trim()
					Character = 'Character=' + $toon.Character.Trim()
					EQPath = 'EQPath=' + $toon.EQPath.Trim()
				}
			}
		}
		Clear-Host
		Update-Display '----Copy/Paste lines below into custom MQ2AutoLogon.ini script----' -color 'Orange'
		$list2 = @()
		$list2 += ''
		foreach ($i in $ini)
		{
			$list2 += $i.Login
			$list2 += $i.Password
			$list2 += $i.Server
			$list2 += $i.Character
			$list2 += $i.EQPath
			$list2 += ''
		}
		Update-Display $list2
		Update-Display '----Copy/Paste lines above into custom MQ2AutoLogon.ini script----' -color 'Orange'
		
		buttonup
	}
	
	$buttonBuildSampleTOONSCSV_Click = {
		buttondown
		$richtextbox1.Clear()
		$nums = 1 .. 12
		$ini = @()
		foreach ($n in $nums)
		{
			$n
			if ($n -eq 7)
			{
				$ini += [pscustomobject]@{
					Login	  = ''
					Password  = ''
					Server    = ''
					Character = ''
					EQPath    = ''
				}
			}
			$ini += [pscustomobject]@{
				Login = 'Login' + $n
				Password = 'PassWord!'
				Server = 'peqtgc'
				Character = 'ToonName' + $n
				EQPath = 'C:\Users\user\Desktop\RoF2\Everquest'
			}
			
		}
		$savefiledialog1.Title = "Save Sample TOONS.CSV"
		#$openfiledialog1.InitialDirectory = $share
		#$openfiledialog1.DefaultExt = "CSV"
		$savefiledialog1.Filter = "CSV (*.csv)|*.CSV|All files (*.*)|*.*"
		$savefiledialog1.FileName = 'Toons-Sample.csv'
		if ($savefiledialog1.ShowDialog() -eq 'OK')
		{
			Update-Display "Exporting to CSV..." -color 'Orange'
			$ini | Export-Csv -path $savefiledialog1.FileName -Delimiter "," -NoTypeInformation
			Update-Display "File saved to:" -color 'Orange'
			Update-Display "File:///$($savefiledialog1.Filename)"
			
		}
		else
		{
			Update-Display 'Operation Cancelled' -color 'Red'
		}
		
		buttonup
		
	}
	
	$richtextbox1_LinkClicked = [System.Windows.Forms.LinkClickedEventHandler]{
		#Event Argument: $_ = [System.Windows.Forms.LinkClickedEventArgs]
		Start-Process -FilePath $_.LinkText #make links clickable
		
	}
	
	$buttonEQCPUAffinity_Click = {
		buttondown
		$richtextbox1.Clear()
		$EQRunning = get-process -Name eqgame | Select-Object -ExpandProperty MainWindowTitle
		if ($EQRunning -ne $null)
		{
			Update-Display 'Setting CPU affinity for all running Everquest processes...' -color 'Orange'
			Start-Sleep -Seconds 1
			$process = GET-PROCESS eqgame
			foreach ($i in $process)
			{
				$i.ProcessorAffinity = 255
				if ($i.ProcessorAffinity -eq 255)
				{
					Update-Display "$($i.MainWindowTitle) set to affinity" -color 'Green'
				}
				else
				{
					Update-Display "$($i.MainWindowTitle) not set to affinity" -color 'Red'
				}
			}
			<#
			Start-Sleep -Seconds 1
			$process = GET-PROCESS eqgame
			foreach ($i in $process)
			{
				if ($i.ProcessorAffinity -eq 255)
				{
					Update-Display "$($i.MainWindowTitle) set to affinity" -color 'Green'
				}
				else
				{
					Update-Display "$($i.MainWindowTitle) not set to affinity" -color 'Red'
				}
			}#>
		}
		else
		{
			Update-Display 'Everquest is not running!' -color 'Yellow'
		}
		buttonup
	}
	
	$buttonKillAllEQWindows_Click = {
		buttondown
		$richtextbox1.Clear()
		$EQRunning = get-process -Name eqgame | Select-Object -ExpandProperty MainWindowTitle
		if ($EQRunning -ne $null)
		{
			Update-Display 'Killing all Everquest processes...' -color 'Orange'
			Start-Sleep -Seconds 1
			taskkill /f /t /im eqgame.exe
		}
		else
		{
			Update-Display 'Everquest is not running!' -color 'Yellow'
		}
		buttonup
	}
	
	$buttonstartMissingToons_Click = {
		buttondown
		$richtextbox1.Clear()
		$EQNotRunningShortcuts = @()
		$list = @()
		$MissingToons = @()
		$EQRunning = get-process -Name eqgame | Select-Object -ExpandProperty MainWindowTitle
		if ($EQRunning -ne $null)
		{
			$Shortcuts = Get-ChildItem -Path $ShortcutsFolder.Text
			foreach ($S in $Shortcuts)
			{
				$list += $S.BaseName
			}
			$EQNotRunning = (Compare-Object -ReferenceObject $EQRunning -DifferenceObject $list).InputObject | Sort-Object
			
			foreach ($Shortcut in $Shortcuts)
			{
				if ($EQNotRunning -contains $Shortcut.BaseName)
				{
					Update-Display "$($Shortcut.BaseName) Not Running" -color 'Yellow'
					$EQNotRunningShortcuts += $Shortcut
					
				}
			}
			#Build AutoHotKey
			$AHKTopLines = @"
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
#Warn  ; Recommended for catching common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

"@
			
			$MissingToons = foreach ($EQNotRunningShortcut in $EQNotRunningShortcuts)
			{
				'Run ' + $EQNotRunningShortcut.FullName
				'WinWaitActive, EverQuest'
				'WinSetTitle, ' + $EQNotRunningShortcut.Name
				''
			}
			
			$AHKTopLines | Out-File $ENV:TEMP\missing.AHK
			$MissingToons | Out-File $ENV:TEMP\missing.AHK -Append
			Start-Sleep -Seconds 2
			Update-Display 'Re-starting missing toons' -color 'Green'
			Start-Process $ENV:TEMP\missing.AHK
		}
		elseif ($EQRunning -eq $null)
		{
			Update-Display 'Everquest is not running!' -color 'Yellow'
		}
		else
		{
			Update-Display 'No missing toons found' -color 'Green'
		}
		buttonup
	}
	
	$buttonBrowseFolder_Click = {
		if ($folderbrowserdialog4.ShowDialog() -eq 'OK')
		{
			$ShortcutsFolder.Text = $folderbrowserdialog4.SelectedPath + '\'
		}
	}
	
	$ShortcutsFolder_TextChanged = {
		button-check
		
	}
	
	$buttonSaveAsDefaultLocatio_Click = {
		buttondown
		$richtextbox1.Clear()
		$currentPWD = Convert-path (get-location)
		Update-Display "Saving PEQConfig.ini to:" -color 'Orange'
		Update-Display "File:///$currentPWD"
		Start-Sleep -Seconds 1
		$ToonsLocation = @{ "ToonsLocation" = "$($toonsFile.Text)" }
		$ShortcutsLocation = @{ "ShortcutsLocation" = "$($ShortcutsFolder.Text)" }
		$NewINIContent = @{ "Paths" = $ToonsLocation + $ShortcutsLocation }
		Out-IniFile -InputObject $NewINIContent -FilePath ".\PEQConfig.ini" -Force
		buttonup
		
	}
	
	$aboutToolStripMenuItem_Click = {
		Update-Display "PEQ Configurator is designed to ease pre-configuration when working with multiple toons and accounts. A CSV file is needed along with an install of Everquest, MQ2, and AutoHotKey.  All accounts should be pre-created on http://www.eqemulator.org/. The CSV creation is a manual step but a sample is supplied to get you started. `nPEQ Configurator is provided as-is.  Feel free to modify the code and redistribute as desired.  `n`nZuboo" -color 'Orange'
		
		
	}
	
	
	$buttonEQClientiniReadOnly_Click = {
		buttondown
		$richtextbox1.Clear()
		$file = Get-ItemProperty $combobox1.SelectedItem
		if ($file.IsReadOnly -eq $true)
		{
			Update-Display "Removing read-only attribute from:" -color 'Orange'
			Update-Display "$file"
			Set-ItemProperty $file -name IsReadOnly -value $False
		}
		else
		{
			Update-Display "Setting read-only attribute for:" -color 'Orange'
			Update-Display "$file"
			Set-ItemProperty $file -name IsReadOnly -value $true
		}
		$file = Get-ItemProperty $combobox1.SelectedItem #get item-property and verify
		if ($file.IsReadOnly -eq $true)
		{
			Update-Display "$file is Read-Only" -color 'Yellow'
		}
		else
		{
			Update-Display "$file is not Read-Only" -color 'Green'
		}
		buttonup
		
	}
	
	#region Control Helper Functions
	function Update-ComboBox
	{
	<#
		.SYNOPSIS
			This functions helps you load items into a ComboBox.
		
		.DESCRIPTION
			Use this function to dynamically load items into the ComboBox control.
		
		.PARAMETER ComboBox
			The ComboBox control you want to add items to.
		
		.PARAMETER Items
			The object or objects you wish to load into the ComboBox's Items collection.
		
		.PARAMETER DisplayMember
			Indicates the property to display for the items in this control.
			
		.PARAMETER ValueMember
			Indicates the property to use for the value of the control.
		
		.PARAMETER Append
			Adds the item(s) to the ComboBox without clearing the Items collection.
		
		.EXAMPLE
			Update-ComboBox $combobox1 "Red", "White", "Blue"
		
		.EXAMPLE
			Update-ComboBox $combobox1 "Red" -Append
			Update-ComboBox $combobox1 "White" -Append
			Update-ComboBox $combobox1 "Blue" -Append
		
		.EXAMPLE
			Update-ComboBox $combobox1 (Get-Process) "ProcessName"
		
		.NOTES
			Additional information about the function.
	#>
		
		param
		(
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			[System.Windows.Forms.ComboBox]$ComboBox,
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			$Items,
			[Parameter(Mandatory = $false)]
			[string]$DisplayMember,
			[Parameter(Mandatory = $false)]
			[string]$ValueMember,
			[switch]$Append
		)
		
		if (-not $Append)
		{
			$ComboBox.Items.Clear()
		}
		
		if ($Items -is [Object[]])
		{
			$ComboBox.Items.AddRange($Items)
		}
		elseif ($Items -is [System.Collections.IEnumerable])
		{
			$ComboBox.BeginUpdate()
			foreach ($obj in $Items)
			{
				$ComboBox.Items.Add($obj)
			}
			$ComboBox.EndUpdate()
		}
		else
		{
			$ComboBox.Items.Add($Items)
		}
		
		$ComboBox.DisplayMember = $DisplayMember
		$ComboBox.ValueMember = $ValueMember
	}
	#endregion
	
	
	
	$combobox1_Click = {
		$ini = @()
		$eqclientlist = @()
		$richtextbox1.Clear()
		if ($toonsFile.Text)
		{
			$toons = Import-Csv -Path $toonsFile.Text #Toons CSV location
			foreach ($toon in $toons)
			{
				if ($toon.Login -ne '')
				{
					$ini += [pscustomobject]@{
						Login = $toon.Login.Trim()
						Password = $toon.Password.Trim()
						Server = $toon.Server.Trim()
						Character = $toon.Character.Trim()
						EQPath = $toon.EQPath.Trim()
					}
				}
			}
			$comboData = $ini.EQPath | Select-Object -Unique
			foreach ($c in $comboData)
			{
				$eqclient = $c + '\eqclient.ini'
				$eqclientlist += $eqclient
				$file = Get-ItemProperty $eqclient
				if ($file.IsReadOnly -eq $true)
				{
					Update-Display "$file is Read-Only" -color 'Yellow'
				}
				else
				{
					Update-Display "$file is not Read-Only" -color 'Green'
				}
			}
			Update-ComboBox -ComboBox $combobox1 -Items $eqclientlist
			If ($combobox1.SelectedText -ne "")
			{
				$buttonEQClientiniReadOnly.Enabled = $true
			}
			else
			{
				$buttonEQClientiniReadOnly.Enabled = $false
			}
		}
		else
		{
			Update-Display "There seems to be a problem accessing toons.csv" -color 'Yellow'
			Update-ComboBox -ComboBox $combobox1 -Items ""
			$buttonEQClientiniReadOnly.Enabled = $false
		}
		
	}
	
	$combobox1_SelectedIndexChanged={
		If ($combobox1.SelectedItem -ne "")
		{
			$buttonEQClientiniReadOnly.Enabled = $true
		}
		else
		{
			$buttonEQClientiniReadOnly.Enabled = $false
		}
	
	}
	
	$buttonTaskbarGroupingFix_Click={
		buttondown
		Start-Sleep -Milliseconds 500
		$richtextbox1.Clear()
		if (Test-Path -Path Registry::HKEY_CLASSES_ROOT\Applications\eqgame.exe)
		{
			$RegValue = Get-ItemProperty -path Registry::HKEY_CLASSES_ROOT\Applications\eqgame.exe -Name IsHostApp
			if ($RegValue.IsHostApp -eq "")
			{
				Update-Display "Registry value IsHostApp already set - Aborting Operation." -color 'Yellow'
			}
			else
			{
				Update-Display "Setting registry value IsHostApp to null" -color 'Orange'
				Set-ItemProperty -path Registry::HKEY_CLASSES_ROOT\Applications\eqgame.exe -Name IsHostApp -Value "" -Type String
			}
			
		}
		else
		{
			Update-Display "HKEY_CLASSES_ROOT\Applications\eqgame.exe not found.  Aborting operation." -color 'Yellow'
		}
		buttonup
		
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$MainForm.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_ShortcutsFolder = $ShortcutsFolder.Text
		$script:MainForm_richtextbox1 = $richtextbox1.Text
		$script:MainForm_toonsFile = $toonsFile.Text
		$script:MainForm_combobox1 = $combobox1.Text
		$script:MainForm_combobox1_SelectedItem = $combobox1.SelectedItem
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonSaveAsDefaultLocatio.remove_Click($buttonSaveAsDefaultLocatio_Click)
			$buttonBrowseFolder.remove_Click($buttonBrowseFolder_Click)
			$ShortcutsFolder.remove_TextChanged($ShortcutsFolder_TextChanged)
			$buttonBuildSampleTOONSCSV.remove_Click($buttonBuildSampleTOONSCSV_Click)
			$richtextbox1.remove_LinkClicked($richtextbox1_LinkClicked)
			$buttonBuildMQ2AutoLogin.remove_Click($buttonBuildMQ2AutoLogin_Click)
			$buttonBuildAutoHotKey.remove_Click($buttonBuildAutoHotKey_Click)
			$buttonBuildShortcuts.remove_Click($buttonBuildShortcuts_Click)
			$buttonBrowse.remove_Click($buttonBrowse_Click)
			$toonsFile.remove_TextChanged($toonsFile_TextChanged)
			$buttonEQCPUAffinity.remove_Click($buttonEQCPUAffinity_Click)
			$buttonKillAllEQWindows.remove_Click($buttonKillAllEQWindows_Click)
			$buttonstartMissingToons.remove_Click($buttonstartMissingToons_Click)
			$combobox1.remove_SelectedIndexChanged($combobox1_SelectedIndexChanged)
			$combobox1.remove_Click($combobox1_Click)
			$buttonTaskbarGroupingFix.remove_Click($buttonTaskbarGroupingFix_Click)
			$buttonEQClientiniReadOnly.remove_Click($buttonEQClientiniReadOnly_Click)
			$MainForm.remove_Load($MainForm_Load)
			$aboutToolStripMenuItem.remove_Click($aboutToolStripMenuItem_Click)
			$MainForm.remove_Load($Form_StateCorrection_Load)
			$MainForm.remove_Closing($Form_StoreValues_Closing)
			$MainForm.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$MainForm.SuspendLayout()
	$menustrip1.SuspendLayout()
	$groupbox1.SuspendLayout()
	$tabcontrol1.SuspendLayout()
	$tabpage1.SuspendLayout()
	$tabpage2.SuspendLayout()
	$CPU.SuspendLayout()
	#
	# MainForm
	#
	$MainForm.Controls.Add($buttonSaveAsDefaultLocatio)
	$MainForm.Controls.Add($buttonBrowseFolder)
	$MainForm.Controls.Add($ShortcutsFolder)
	$MainForm.Controls.Add($labelShortcutsLocation)
	$MainForm.Controls.Add($buttonBuildSampleTOONSCSV)
	$MainForm.Controls.Add($labelPEQConfigurator)
	$MainForm.Controls.Add($richtextbox1)
	$MainForm.Controls.Add($buttonBuildMQ2AutoLogin)
	$MainForm.Controls.Add($buttonBuildAutoHotKey)
	$MainForm.Controls.Add($buttonBuildShortcuts)
	$MainForm.Controls.Add($labelToonsCsvLocation)
	$MainForm.Controls.Add($buttonBrowse)
	$MainForm.Controls.Add($toonsFile)
	$MainForm.Controls.Add($menustrip1)
	$MainForm.Controls.Add($groupbox1)
	$MainForm.AutoScaleDimensions = '6, 13'
	$MainForm.AutoScaleMode = 'Font'
	$MainForm.ClientSize = '678, 701'
	$MainForm.FormBorderStyle = 'FixedDialog'
	$MainForm.MainMenuStrip = $menustrip1
	$MainForm.Margin = '4, 4, 4, 4'
	$MainForm.MaximizeBox = $False
	$MainForm.Name = 'MainForm'
	$MainForm.StartPosition = 'CenterScreen'
	$MainForm.Text = 'PEQ Configurator'
	$MainForm.add_Load($MainForm_Load)
	#
	# buttonSaveAsDefaultLocatio
	#
	$buttonSaveAsDefaultLocatio.Location = '22, 210'
	$buttonSaveAsDefaultLocatio.Name = 'buttonSaveAsDefaultLocatio'
	$buttonSaveAsDefaultLocatio.Size = '275, 38'
	$buttonSaveAsDefaultLocatio.TabIndex = 19
	$buttonSaveAsDefaultLocatio.Text = 'Save as Default Locations'
	$buttonSaveAsDefaultLocatio.UseCompatibleTextRendering = $True
	$buttonSaveAsDefaultLocatio.UseVisualStyleBackColor = $True
	$buttonSaveAsDefaultLocatio.add_Click($buttonSaveAsDefaultLocatio_Click)
	#
	# buttonBrowseFolder
	#
	$buttonBrowseFolder.Location = '303, 181'
	$buttonBrowseFolder.Name = 'buttonBrowseFolder'
	$buttonBrowseFolder.Size = '30, 23'
	$buttonBrowseFolder.TabIndex = 4
	$buttonBrowseFolder.Text = '...'
	$buttonBrowseFolder.UseCompatibleTextRendering = $True
	$buttonBrowseFolder.UseVisualStyleBackColor = $True
	$buttonBrowseFolder.add_Click($buttonBrowseFolder_Click)
	#
	# ShortcutsFolder
	#
	$ShortcutsFolder.AutoCompleteMode = 'SuggestAppend'
	$ShortcutsFolder.AutoCompleteSource = 'FileSystemDirectories'
	$ShortcutsFolder.BackColor = 'Info'
	$ShortcutsFolder.Location = '21, 184'
	$ShortcutsFolder.Name = 'ShortcutsFolder'
	$ShortcutsFolder.Size = '276, 20'
	$ShortcutsFolder.TabIndex = 3
	$ShortcutsFolder.add_TextChanged($ShortcutsFolder_TextChanged)
	#
	# labelShortcutsLocation
	#
	$labelShortcutsLocation.AutoSize = $True
	$labelShortcutsLocation.Location = '22, 167'
	$labelShortcutsLocation.Name = 'labelShortcutsLocation'
	$labelShortcutsLocation.Size = '98, 17'
	$labelShortcutsLocation.TabIndex = 18
	$labelShortcutsLocation.Text = 'Shortcuts Location'
	$labelShortcutsLocation.UseCompatibleTextRendering = $True
	#
	# buttonBuildSampleTOONSCSV
	#
	$buttonBuildSampleTOONSCSV.Location = '22, 327'
	$buttonBuildSampleTOONSCSV.Name = 'buttonBuildSampleTOONSCSV'
	$buttonBuildSampleTOONSCSV.Size = '88, 56'
	$buttonBuildSampleTOONSCSV.TabIndex = 13
	$buttonBuildSampleTOONSCSV.Text = 'Build Sample Toons.Csv ...'
	$buttonBuildSampleTOONSCSV.UseCompatibleTextRendering = $True
	$buttonBuildSampleTOONSCSV.UseVisualStyleBackColor = $True
	$buttonBuildSampleTOONSCSV.add_Click($buttonBuildSampleTOONSCSV_Click)
	#
	# labelPEQConfigurator
	#
	$labelPEQConfigurator.AutoSize = $True
	$labelPEQConfigurator.Font = 'Arial Black, 18pt'
	$labelPEQConfigurator.Location = '22, 51'
	$labelPEQConfigurator.Name = 'labelPEQConfigurator'
	$labelPEQConfigurator.Size = '242, 40'
	$labelPEQConfigurator.TabIndex = 12
	$labelPEQConfigurator.Text = 'PEQ Configurator'
	$labelPEQConfigurator.UseCompatibleTextRendering = $True
	#
	# richtextbox1
	#
	$richtextbox1.BackColor = '1, 36, 86'
	$richtextbox1.Font = 'Consolas, 11pt'
	$richtextbox1.Location = '11, 412'
	$richtextbox1.Name = 'richtextbox1'
	$richtextbox1.ReadOnly = $True
	$richtextbox1.Size = '653, 284'
	$richtextbox1.TabIndex = 11
	$richtextbox1.Text = ''
	$richtextbox1.add_LinkClicked($richtextbox1_LinkClicked)
	#
	# buttonBuildMQ2AutoLogin
	#
	$buttonBuildMQ2AutoLogin.Location = '210, 266'
	$buttonBuildMQ2AutoLogin.Name = 'buttonBuildMQ2AutoLogin'
	$buttonBuildMQ2AutoLogin.Size = '88, 56'
	$buttonBuildMQ2AutoLogin.TabIndex = 9
	$buttonBuildMQ2AutoLogin.Text = 'Build MQ2AutoLogin INI'
	$buttonBuildMQ2AutoLogin.UseCompatibleTextRendering = $True
	$buttonBuildMQ2AutoLogin.UseVisualStyleBackColor = $True
	$buttonBuildMQ2AutoLogin.add_Click($buttonBuildMQ2AutoLogin_Click)
	#
	# buttonBuildAutoHotKey
	#
	$buttonBuildAutoHotKey.Location = '116, 266'
	$buttonBuildAutoHotKey.Name = 'buttonBuildAutoHotKey'
	$buttonBuildAutoHotKey.Size = '88, 56'
	$buttonBuildAutoHotKey.TabIndex = 8
	$buttonBuildAutoHotKey.Text = 'Build AutoHotKey Script'
	$buttonBuildAutoHotKey.UseCompatibleTextRendering = $True
	$buttonBuildAutoHotKey.UseVisualStyleBackColor = $True
	$buttonBuildAutoHotKey.add_Click($buttonBuildAutoHotKey_Click)
	#
	# buttonBuildShortcuts
	#
	$buttonBuildShortcuts.Location = '22, 265'
	$buttonBuildShortcuts.Name = 'buttonBuildShortcuts'
	$buttonBuildShortcuts.Size = '88, 56'
	$buttonBuildShortcuts.TabIndex = 7
	$buttonBuildShortcuts.Text = 'Build Shortcuts...'
	$tooltip1.SetToolTip($buttonBuildShortcuts, 'Overwrites any previous shortcuts!')
	$buttonBuildShortcuts.UseCompatibleTextRendering = $True
	$buttonBuildShortcuts.UseVisualStyleBackColor = $True
	$buttonBuildShortcuts.add_Click($buttonBuildShortcuts_Click)
	#
	# labelToonsCsvLocation
	#
	$labelToonsCsvLocation.AutoSize = $True
	$labelToonsCsvLocation.Location = '21, 121'
	$labelToonsCsvLocation.Name = 'labelToonsCsvLocation'
	$labelToonsCsvLocation.Size = '117, 17'
	$labelToonsCsvLocation.TabIndex = 6
	$labelToonsCsvLocation.Text = 'TOONS.CSV Location'
	$labelToonsCsvLocation.UseCompatibleTextRendering = $True
	#
	# buttonBrowse
	#
	$buttonBrowse.Location = '303, 138'
	$buttonBrowse.Name = 'buttonBrowse'
	$buttonBrowse.Size = '30, 23'
	$buttonBrowse.TabIndex = 1
	$buttonBrowse.Text = '...'
	$buttonBrowse.UseCompatibleTextRendering = $True
	$buttonBrowse.UseVisualStyleBackColor = $True
	$buttonBrowse.add_Click($buttonBrowse_Click)
	#
	# toonsFile
	#
	$toonsFile.AutoCompleteMode = 'SuggestAppend'
	$toonsFile.AutoCompleteSource = 'FileSystem'
	$toonsFile.BackColor = 'Info'
	$toonsFile.Location = '21, 138'
	$toonsFile.Name = 'toonsFile'
	$toonsFile.Size = '276, 20'
	$toonsFile.TabIndex = 0
	$toonsFile.add_TextChanged($toonsFile_TextChanged)
	#
	# menustrip1
	#
	[void]$menustrip1.Items.Add($helpToolStripMenuItem)
	$menustrip1.Location = '0, 0'
	$menustrip1.Name = 'menustrip1'
	$menustrip1.Size = '678, 24'
	$menustrip1.TabIndex = 21
	$menustrip1.Text = 'menustrip1'
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($tabcontrol1)
	$groupbox1.Controls.Add($CPU)
	$groupbox1.Location = '11, 27'
	$groupbox1.Name = 'groupbox1'
	$groupbox1.Size = '653, 380'
	$groupbox1.TabIndex = 23
	$groupbox1.TabStop = $False
	$groupbox1.UseCompatibleTextRendering = $True
	#
	# tabcontrol1
	#
	$tabcontrol1.Controls.Add($tabpage1)
	$tabcontrol1.Controls.Add($tabpage2)
	$tabcontrol1.Location = '343, 10'
	$tabcontrol1.Name = 'tabcontrol1'
	$tabcontrol1.SelectedIndex = 0
	$tabcontrol1.Size = '299, 285'
	$tabcontrol1.TabIndex = 22
	#
	# tabpage1
	#
	$tabpage1.Controls.Add($buttonEQCPUAffinity)
	$tabpage1.Controls.Add($buttonKillAllEQWindows)
	$tabpage1.Controls.Add($buttonstartMissingToons)
	$tabpage1.BackColor = 'Transparent'
	$tabpage1.Location = '4, 22'
	$tabpage1.Name = 'tabpage1'
	$tabpage1.Padding = '3, 3, 3, 3'
	$tabpage1.Size = '291, 259'
	$tabpage1.TabIndex = 0
	$tabpage1.Text = 'Utilities'
	#
	# buttonEQCPUAffinity
	#
	#region Binary Data
	$buttonEQCPUAffinity.Image = [System.Convert]::FromBase64String('
iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABGdBTUEAALlrZELNbAAAACBjSFJN
AACHCgAAjCAAAP5TAACDgAAAfvwAAOlWAAA+EQAAIt5KhyhXAAAE1WlDQ1BJQ0MgUHJvZmlsZQAA
SMfllntMFEccx3+79wYO7uA8pDw8KUWkB70CSk8I4VGkIAICglhy5V7CCXdslgNBWoFCCr7wAVVp
aFGCgpLWBsUixfqiQiChiClSrCKexgcPFQsJD73Oco0kNTXp33yTyXzmtzO/2Znd784CsM/KCSID
BwCtTk/GhgWLNiVtFrH6gQlsEIAN2MiVWURQTEwk/Kem+gGj6hseVK7GyLXquy131joPK3aOnfdQ
wdvFJdGEAJgIsSDVxD4UK0z8CcXb9IQecTLFyjQ5yokRiMVkfGwI4mrEc6nzjB+hWDHPtEqKc5Sp
aCx9P2KJTqXRIb6Erlmq1FlKAFYviu9SEiTqw6bye2i1mSg/ew9iN2ovTLeZWQIgPYnyOy7EUlD5
MRVA+HQhtiIWtW0BWoULsRfL5vcH++inrC3eXvMhjN+K5nAxGserAMzKAV6uMRpn+EbjXB8AQwzQ
6KTMJnP+2aNcVGhgBrawEoJABkVwCgYxPhaNVWLDuC9+CH9FI2ijdJJBZxxjhjNfsS6y93DUZhHm
/hZruCGWiVY5vFr+mM0mwV1h0dLVdtP27Y77lsUspzu3ueS7BrtZrbz//mWPEx9UfFjmXbqq3Peo
tM3PECAMTAiu/Xg2LCW8LzI6amCDNt4ioTlJk+wqG5W3qvanZmyN1voSLlmCHFbuXP7zHQ+KbpZ0
lrbsath7ZH9ZRf4hokpTvaVGU0seL274rrH9h8kmn+biFkPbxou3r2Z3CLuu9OT1+fdz/xi9PTg8
8ODRE/PxoIm9U89m043GN9ZuAfYggXWgha+hHaax1dh27Bpuh+vxAVoorZUupV9mxDGeMg+x1rIx
dgfnsBlpnmgRxg2yDLWK5Wn45dbtAvMlCmHX0iC7TnuZI+Z0RkQ4+7vYumIrZtxBLPD0lsi8Knyu
+wqlCr+mAHrgpuCzoY5hFRFLImuj/TYMxe9NDN3MSO757FtFljoqzTOdp50kBrN+yTmWV/h5UoG4
aKrkXKl2l8OeX/elHWRV1h0OrLpTvaPG5dj1utL6iFMO38Pp6TOcc6vOF7SNXipod+sY6q7/rfRG
8c2aW4a7cfcnH/eOj/wVOT37xtpx4CAfvgu+EAM6OAg/wxNMhCVjR7ERPACvwl/S0mkGuor+nFHG
dGcOsA6wEzluZgyzcfN7FsPcUSvgOfJjresFdkvqbdfbsd7pdahzyhdFO7u7WLuy3DjutmKJZ5yk
0KvZ57mvtzTP70oAFz33E6EQpkLPPSKqa0N83MOEL5Pe+7RXViz3V85tuaIpz5BlepNc/eNtndtP
frG7UFcc9ZX7TvruW+VNB8oqUw5Lv7Gtnqkx1P5+vLdhoHHstHVTeHNly1QbeYlz9WzH1m6PHmOf
of/PwZEhgSHp4YXR0GcTk50z3Uajyasmh5i+KZQeFS3wi7TXjGqTnynRmAB1pQAbDQDrrgFURQC4
+gPYIC/HcAHipYDdUwI2vBywJ3z0RuUCvthctdictNjcA2A60+bF06yXK0Uh8gyNgpTr1a+PYR5o
YD3IQQkiCEF1BmorgESkBzWo3jb0/0mvzp33ckgmkUdqUtP0oiD0d6AWhWRqiWy9mhSLwnVKT7HI
SyLxpvqZzl1KTB5A9WaKLkzI/pUV4G9ud9tQ9PDCzAAACFpJREFUWEe9l3lQVFcWxt9sNXtm+SM4
jktJg4LRRAPG0aBTiOCOomOigsoAYkBlUdAG2gWQBBUwLhFRR4FRVBRlExQMKCggitKAqOAMItos
Qm8sAQS/OefR/SZUrFTiVOZW/erevvec+33vvPOqQHB2dn7r2LFjy+Lj49d9G4mJid+A9w8ePLju
9OnTrz37NliTtYVDhw7N7O7uxpsgCMJr978rsbGxMwRy68c/bG1t/6+wZkJCgq/A5eAfMvtE2Mvz
iBwsjbwBt9gyrDlyFz5J5dh4rhz+yUr4n1Ei4LwSWy9XQpFdiRAjWQMoLjEVA2RWICSjAkHpFZCn
VSIwtQIbU5QIyqgVtViTtYWjR49KBpxinsMpug6ux5oQmN2F4NwuhBV147M7XyGiuBsxyl4cePQS
Mfd7EV3F9AxQ2YuoCgPKHqIXe8p7sPtuD3YREXe6EVbyFUIL6a7bkAyw9iADjpF1cPysFh9/Xg/f
C2rIr2ixNV+HHYV6RJS0k3gnwm/pEVb8NYr0CGVuDrDjBlFAa56LdAi5rsOWXC2CiO3XdIipeDXY
QFxcnGRgfsQTzNtZi0W76+B5shVbyEDwlzpsL9ThQE0nIu+2IyRPBwVdpCBjRniPCbo6gKKAoJzN
V7XYeFkDeZ5WNBteoseue/2SAdYW+DMyGpgdVodZOx5hbthjrIxrhl+6FiEkEFPdgf21nZB/qUXA
ZS0CyVgAQ2tmE4n4X9LQTPE3dJAXknAO7V2hvasasQrBdA+b2174UjLA2oMM2G17jBkh1bALeYgl
e5/B84waYVTyo6ouRNDTr0/VwCddgw1M2gC898l5NTaRoW2lemy+roUfCfuSgQ3ZNGeRCZr9yKBv
BsVRbw0ysHfvXsnAdPkjTAuoIu5jVvi/sDqxFbsqO3CEDGzM1sLjtBqeZwdYc6YN7kltcKWYwBwt
Pq1sR2CBVhReTxVZm66GBxnzvqiGV0obPJNb4H66keKbJAOsLURHR0sGpmysxmTfckzyuYdp8gdw
T36BmNoOfKpsh0v8C6yMb8HKEy1wOd6MFceasexIE/wvq7G7mnqjWAefXA28stRwT1FjZVIrVp16
QaKtcE2inAQVFu+rwYKoGskAawuRkZGSAasNFZiwtgTj3IpgE1QNbypfWLkebufasPRoE/4WqyLo
Uz34DIuI9Zmt2EnnW2/p4Evvem2mGqvPtmF54gssYYNkeMVJWh9ugP3OKthuLcPMsCrJAGsL4eHh
koHxa0phubIAFi4FsI98QhdqsDq5FQtjm7HocCPm0ec5J7oec2Pq4XHhhfjUwdR0ftTtnlRy5zOt
WEIVcoxrguPhZiyhSjnsqsWULWXEbaIEU0PuSgZYWwgNDZUMWDoXwHxxNt51v4k5nz8nURVmRT3F
7OgBZkQ8hm14DT4+3oT11BN+9O69qbk86D0vp3IvpCrNPqiCw34V7KLqMXnzPbznVYSJG4pg5VcM
K/+bsN5UJBlg7UEGxjhlwWzeBVj73cP00Mf4UPEQNooHIh+GPMBUeRXsImqwNK6B+qERK040Ytk/
GrEkToU5+xowc089pkf8G9aBVbB0vYExq/Ix9u959Eqv4p3V2VTZVFisSh1sQKFQSAbMZp4lExnk
uAwT190iSjHR+xYmGJjkfwfTgsphv6MSDqH34RBWjVk7H8IujIxuewBrfyUJ3cDoj3JhvjAd5o4p
MJ+fDLP5ZyBbcAoypyRYLE+RDLC2EBwcLBmQzUjCmI8uw8I5FxYrcmC5PIcSiGVXMNblKsatzsME
93xYeV6H9dpCfOB9E5M33IK1dwnecc6D+YI0mM0hgZlJGDXtOExt4yFz+CftnYIZGTBnA0vPSwZY
WwgMDJQMjLZLhvm8i+Sa4HnuBZjPTsFoWo9ekIrR89MwxpGgp7NwysTYxVmwXJgJc4dzkP31JGTT
EiCbngBTmxPEcchs6TdXdtZJuusU5Z+ieIo1GGBtwcfHRzQw5H2FiIm1gfdDYDKR4NlqgCFWWzHE
ehudE7Q2eU+Ot8dvNhCAt8dt+u/8bgBMJgRS/maKlcNkkhxDPgjCn/5Cd5AOa7K24OXlJRpobm6G
Wq2GVquFTqcTaW9vR2dnp0hXV5eYZKS3t3cQXz/jWGNeR0eHdB/fzRqsxXGsLXh4eIgG6urq8OTJ
Ezx9+hQNDQ149uwZVCoVmpqaRFpaWtDa2oq2tjYRo1GeGeM+x3Asi3BeY2OjeBffyXfX19eLWqzJ
2oKbm9sbGdBoNNKlb2qAtd/IAJeR57KyMlRVVf1vBlxdXT+hH/0k3k+H/d+nAs+fPxfh9Xcw8Iru
Zo0+0upjTRcXl7VsYBk1ipbEXlLwK07iZKMgP62xOfV6vfTeuUG5wRhe8x6fcQyv2ZSxUkZDBlP9
pNNHeWrSXipYWVnJrl27lkVDdfHiRQ2hTU9P12VmZuoyMjL0ly5d0mdnZ+tzc3P1FKPLycnpz8/P
x+vgM47hWM6htZhjuEubmpqqIdS010CaF2xsbEbQ/xbfb9A/E0X0xyT27duHqKgoEV7zHp8Zwn64
UV1dXcYl5VfFPWLsE97jM0PYDzPS0tJsi4uLwZSWloozc/v2bWnNMYbwNxo/IX5O/Ip4i/iDgeHl
5eX6mpoasau50Xp6etDf34++vj5xzY3HX0RtbS2USqWecoYRvyd+R/ya+AXxM4I1fkR8Y/DmbwkT
wpSYQEwl7AinYcOGhQ4fPnyPqanpXplMdsDMzOwLWscyo0aN+mLEiBH7R44cGUPz7qFDh26nHEeC
qzGFGE/IiCEEa/yYeO1gd+z0NwQ/OZvhJ+FuHU6MIvgic8KCsDTAa97js5HEnwnO4Znv+CPBwr8k
fkoYhiD8B3M9CbLmrJUXAAAAAElFTkSuQmCC')
	#endregion
	$buttonEQCPUAffinity.ImageAlign = 'TopCenter'
	$buttonEQCPUAffinity.Location = '6, 7'
	$buttonEQCPUAffinity.Name = 'buttonEQCPUAffinity'
	$buttonEQCPUAffinity.Size = '88, 81'
	$buttonEQCPUAffinity.TabIndex = 8
	$buttonEQCPUAffinity.Text = 'EQ CPU Affinity
'
	$buttonEQCPUAffinity.TextAlign = 'BottomCenter'
	$tooltip1.SetToolTip($buttonEQCPUAffinity, 'Force EQ to all cores')
	$buttonEQCPUAffinity.UseCompatibleTextRendering = $True
	$buttonEQCPUAffinity.UseVisualStyleBackColor = $True
	$buttonEQCPUAffinity.add_Click($buttonEQCPUAffinity_Click)
	#
	# buttonKillAllEQWindows
	#
	#region Binary Data
	$buttonKillAllEQWindows.Image = [System.Convert]::FromBase64String('
iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABGdBTUEAALlrZELNbAAAACBjSFJN
AACHCgAAjCAAAP5TAACDgAAAfvwAAOlWAAA+EQAAIt5KhyhXAAAE1WlDQ1BJQ0MgUHJvZmlsZQAA
SMfllntMFEccx3+79wYO7uA8pDw8KUWkB70CSk8I4VGkIAICglhy5V7CCXdslgNBWoFCCr7wAVVp
aFGCgpLWBsUixfqiQiChiClSrCKexgcPFQsJD73Oco0kNTXp33yTyXzmtzO/2Znd784CsM/KCSID
BwCtTk/GhgWLNiVtFrH6gQlsEIAN2MiVWURQTEwk/Kem+gGj6hseVK7GyLXquy131joPK3aOnfdQ
wdvFJdGEAJgIsSDVxD4UK0z8CcXb9IQecTLFyjQ5yokRiMVkfGwI4mrEc6nzjB+hWDHPtEqKc5Sp
aCx9P2KJTqXRIb6Erlmq1FlKAFYviu9SEiTqw6bye2i1mSg/ew9iN2ovTLeZWQIgPYnyOy7EUlD5
MRVA+HQhtiIWtW0BWoULsRfL5vcH++inrC3eXvMhjN+K5nAxGserAMzKAV6uMRpn+EbjXB8AQwzQ
6KTMJnP+2aNcVGhgBrawEoJABkVwCgYxPhaNVWLDuC9+CH9FI2ijdJJBZxxjhjNfsS6y93DUZhHm
/hZruCGWiVY5vFr+mM0mwV1h0dLVdtP27Y77lsUspzu3ueS7BrtZrbz//mWPEx9UfFjmXbqq3Peo
tM3PECAMTAiu/Xg2LCW8LzI6amCDNt4ioTlJk+wqG5W3qvanZmyN1voSLlmCHFbuXP7zHQ+KbpZ0
lrbsath7ZH9ZRf4hokpTvaVGU0seL274rrH9h8kmn+biFkPbxou3r2Z3CLuu9OT1+fdz/xi9PTg8
8ODRE/PxoIm9U89m043GN9ZuAfYggXWgha+hHaax1dh27Bpuh+vxAVoorZUupV9mxDGeMg+x1rIx
dgfnsBlpnmgRxg2yDLWK5Wn45dbtAvMlCmHX0iC7TnuZI+Z0RkQ4+7vYumIrZtxBLPD0lsi8Knyu
+wqlCr+mAHrgpuCzoY5hFRFLImuj/TYMxe9NDN3MSO757FtFljoqzTOdp50kBrN+yTmWV/h5UoG4
aKrkXKl2l8OeX/elHWRV1h0OrLpTvaPG5dj1utL6iFMO38Pp6TOcc6vOF7SNXipod+sY6q7/rfRG
8c2aW4a7cfcnH/eOj/wVOT37xtpx4CAfvgu+EAM6OAg/wxNMhCVjR7ERPACvwl/S0mkGuor+nFHG
dGcOsA6wEzluZgyzcfN7FsPcUSvgOfJjresFdkvqbdfbsd7pdahzyhdFO7u7WLuy3DjutmKJZ5yk
0KvZ57mvtzTP70oAFz33E6EQpkLPPSKqa0N83MOEL5Pe+7RXViz3V85tuaIpz5BlepNc/eNtndtP
frG7UFcc9ZX7TvruW+VNB8oqUw5Lv7Gtnqkx1P5+vLdhoHHstHVTeHNly1QbeYlz9WzH1m6PHmOf
of/PwZEhgSHp4YXR0GcTk50z3Uajyasmh5i+KZQeFS3wi7TXjGqTnynRmAB1pQAbDQDrrgFURQC4
+gPYIC/HcAHipYDdUwI2vBywJ3z0RuUCvthctdictNjcA2A60+bF06yXK0Uh8gyNgpTr1a+PYR5o
YD3IQQkiCEF1BmorgESkBzWo3jb0/0mvzp33ckgmkUdqUtP0oiD0d6AWhWRqiWy9mhSLwnVKT7HI
SyLxpvqZzl1KTB5A9WaKLkzI/pUV4G9ud9tQ9PDCzAAABzpJREFUWEftl3tQ1NcVx8/eVYPy2OW5
C0sUJUq0kMiYNNihhiGTCMGqicQk2DhOGTHWtFjSBJHw0k0gkQWU91NAjYiKoBKNgEZBg4oPJDEa
nLE1WuNQXyDhz2/PXX4sLg8T2870n35nPsz+7jn3nHPPvfc3P+j/elxVTyFNmY7erPCk6EqDKJRs
cRemzQZaVulBExW3/75K3Cmk3IPqqqZr0Bo1H+1xkbiab8TVAiOubExA2+olqA2YhEoDXSgz0Epl
2n+uYh0Flxto55FFs3GjPB29Xx/AT6ca8NPpRvS1NaHvzBH0nTuKvvPN6Gtvwd2GXTi5KhybPehc
uSdFKWH+PZV4iJTdszxwrSAFvS370Nu81xo5dqIeva0H+4tqO9xfEHO7fgv2/nYqFyI+U8I9nkrd
Rer+IB/cO7AVD47U4EHTTvQ07kBPQxWu5yfjQsxbOBUZilNR83AlNRp3akvRe5yLkR1q/dJMDxd5
LOIllBlElhL2l6mAV/7FK364f2AbemRiTtpzcBuu5yRgz6+fRJEHNZW4UWKxO0UVutHKYndRyFvV
2fLOy7i9hwtp5s7I7jAPjtaicWEASvTCpIR/tHL5sH3u64y7+8o5cTV6vtyObu7C+ejFKNTTVwV8
AxRXK8lCtvu59s87vBs93LV+9uB+ww7UBnpDFqy4j65CHdX9LXMNunnF3V9sQTcHPLvqNeTpRV6u
LekVNyvJosu8xuNmkdHs372/At31Fbi/n3/LGLyAm2VpKDKoUU2kVqYNV64ThewNmo77daVMCe7V
FOHSR5EyeeUmO3JV3KyUraHJBXo1OhP+gDtbTbizLcPMrYIk7Jntha7yT3FvZy7u7crD8d8HI8+F
EpWpw5XtRnWdKStxd0cOk41bxUYUT56AHCearbgMUw53pi0yBLdLjRa6OHn1LHfkugpjw6vP9o9v
TsWPOfG8mFG6kEE0Pt9zHP5Zws5c9e2Kz9C44AVk6ihecRmmTGeR1Rg2E105a62oD/bBRjdhkoly
dAJ/X/+uxbZvzlRkOlKYEmJQcrCO720XV9mVn4ibWbHI1o9FMtE4xcVKG52FcTffiB/T3sOtDdEW
ji18HmzLU9woy1Wknngz0GI/GTHHXJxiHpTJiWKawvw54J9wy/Q+zv9xIdJdRJVitpL0LZ2mwQ/x
S3Fz3XILZ5cGw+QmtqU5kkZxJf4dVhMw0eLTERUKkysdUMyDSudKj87zx42EZfjH+hVoXhwIOaaY
LUp3ovBNnk+gc/UiXI+LsHBx+Vxk6NTghIGKq1kb+Pxs9XW1+H0XFYINLtSmmAeV5iJMX4X64VrM
6/hhzRI0vOovg61RzGbxs1+6bgw6Vr2OG0mRZr9rf3kN368IwSaDDVKdaZniapHsQJW/HtdWLzTT
sfRFpDnRScU8KJ4cv8tL4Jtn1Lj4vB32+WqQ6jj4HpeH9GPe20NzvHFl8Sx0zp+By6944ZtAF+S6
C5l8xMPK4+9VTeyPK2mcJvCJM9Up5kGt11A4v7PR4ac20+yvxXpHalbMZNSK7F3PGXDl7QB0hvvj
+9/NwKW5U1DqZYN12tFfs0YnOnSYkw7EreFFrnMevrWU7EgTN7iocMFXbabjmXHI0o9BooZeTnYU
qaVPOeDyAj9cnu+LS6HT8N1Lk1DtYw+2WU78UCVy+zNcVWhXYkpydSoYh5wTi5K01HxkKjv+qp+D
UwSSNVSTyfve/hs9Ls7xwMVAHb4NcEb907ZI1opK3mPLiR+qZC3tP+QtLPFan1YjRasa/XWc4EgR
Rbyf7TPUFj5/UuBrn8FnyeGn1LxyFeIe8YZMcuDPNA/rWBW8xfFDDvYwxdtTc6O3Guenj8yJaWo+
G5zcgd5RpgzTR3YiK8dN4AyveGBeC3c2iVf/Bh9mxW1krbWliE+dVTjDqz7HAR7mNI9JW6xm5FV8
oKWZazWiUL5+H55/ljHxWYjTUozi+mjF8gryOcjDySXHuPVGXv0aB5G9lg9nLB/c98fRjFgHCotz
EHmJvMLdfOWGzpNbIeco4X+ZYjlgHhdxmlt+llczgHze4SmQ6SqQwsV87KTCRv5dzWfl1BBfSTkn
l7F+tvUj6UN7YZL73TRFjTMc/HFo5T2XXfwrJ+dOjXpTBqRSkNdjLPMEIyu2XzmeYj50UKGIg7XI
Qjjwz1HL3Ujg7Yi2FZkcw4GxVWLK2DLHQD6zBh6kUTq6MF6ML/MCE8Qz571lI7Z8YK9ChovAdr5O
h7zUOM63pY0Tyt/1kwRK9XzNuNjI8dQSNMZ8UIMZeVWfZbwZN8aOkbkEYy5C/pEPclAapZN0nsnI
N9ZcZj6ziD8MlgSNFelLbKhxxQS6+mc76o6xU0H+Xm5L3y6wEVUGonfZN5xZwIQyLzLPMT6M/Ka0
Z+Q3hqWAAcmBMYxs1QRGts6Jkd+CcqIH48nI//8mMbJLkx9CPkub9OE6yJ2Ri3FmtMzANsgcVon/
hyL6FzjJLhSbIZ5LAAAAAElFTkSuQmCC')
	#endregion
	$buttonKillAllEQWindows.ImageAlign = 'TopCenter'
	$buttonKillAllEQWindows.Location = '197, 7'
	$buttonKillAllEQWindows.Name = 'buttonKillAllEQWindows'
	$buttonKillAllEQWindows.Size = '88, 81'
	$buttonKillAllEQWindows.TabIndex = 10
	$buttonKillAllEQWindows.Text = 'Kill All EQ Windows'
	$buttonKillAllEQWindows.TextAlign = 'BottomCenter'
	$buttonKillAllEQWindows.UseCompatibleTextRendering = $True
	$buttonKillAllEQWindows.UseVisualStyleBackColor = $True
	$buttonKillAllEQWindows.add_Click($buttonKillAllEQWindows_Click)
	#
	# buttonstartMissingToons
	#
	#region Binary Data
	$buttonstartMissingToons.Image = [System.Convert]::FromBase64String('
iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABGdBTUEAALlrZELNbAAAACBjSFJN
AACHCgAAjCAAAP5TAACDgAAAfvwAAOlWAAA+EQAAIt5KhyhXAAAE1WlDQ1BJQ0MgUHJvZmlsZQAA
SMfllntMFEccx3+79wYO7uA8pDw8KUWkB70CSk8I4VGkIAICglhy5V7CCXdslgNBWoFCCr7wAVVp
aFGCgpLWBsUixfqiQiChiClSrCKexgcPFQsJD73Oco0kNTXp33yTyXzmtzO/2Znd784CsM/KCSID
BwCtTk/GhgWLNiVtFrH6gQlsEIAN2MiVWURQTEwk/Kem+gGj6hseVK7GyLXquy131joPK3aOnfdQ
wdvFJdGEAJgIsSDVxD4UK0z8CcXb9IQecTLFyjQ5yokRiMVkfGwI4mrEc6nzjB+hWDHPtEqKc5Sp
aCx9P2KJTqXRIb6Erlmq1FlKAFYviu9SEiTqw6bye2i1mSg/ew9iN2ovTLeZWQIgPYnyOy7EUlD5
MRVA+HQhtiIWtW0BWoULsRfL5vcH++inrC3eXvMhjN+K5nAxGserAMzKAV6uMRpn+EbjXB8AQwzQ
6KTMJnP+2aNcVGhgBrawEoJABkVwCgYxPhaNVWLDuC9+CH9FI2ijdJJBZxxjhjNfsS6y93DUZhHm
/hZruCGWiVY5vFr+mM0mwV1h0dLVdtP27Y77lsUspzu3ueS7BrtZrbz//mWPEx9UfFjmXbqq3Peo
tM3PECAMTAiu/Xg2LCW8LzI6amCDNt4ioTlJk+wqG5W3qvanZmyN1voSLlmCHFbuXP7zHQ+KbpZ0
lrbsath7ZH9ZRf4hokpTvaVGU0seL274rrH9h8kmn+biFkPbxou3r2Z3CLuu9OT1+fdz/xi9PTg8
8ODRE/PxoIm9U89m043GN9ZuAfYggXWgha+hHaax1dh27Bpuh+vxAVoorZUupV9mxDGeMg+x1rIx
dgfnsBlpnmgRxg2yDLWK5Wn45dbtAvMlCmHX0iC7TnuZI+Z0RkQ4+7vYumIrZtxBLPD0lsi8Knyu
+wqlCr+mAHrgpuCzoY5hFRFLImuj/TYMxe9NDN3MSO757FtFljoqzTOdp50kBrN+yTmWV/h5UoG4
aKrkXKl2l8OeX/elHWRV1h0OrLpTvaPG5dj1utL6iFMO38Pp6TOcc6vOF7SNXipod+sY6q7/rfRG
8c2aW4a7cfcnH/eOj/wVOT37xtpx4CAfvgu+EAM6OAg/wxNMhCVjR7ERPACvwl/S0mkGuor+nFHG
dGcOsA6wEzluZgyzcfN7FsPcUSvgOfJjresFdkvqbdfbsd7pdahzyhdFO7u7WLuy3DjutmKJZ5yk
0KvZ57mvtzTP70oAFz33E6EQpkLPPSKqa0N83MOEL5Pe+7RXViz3V85tuaIpz5BlepNc/eNtndtP
frG7UFcc9ZX7TvruW+VNB8oqUw5Lv7Gtnqkx1P5+vLdhoHHstHVTeHNly1QbeYlz9WzH1m6PHmOf
of/PwZEhgSHp4YXR0GcTk50z3Uajyasmh5i+KZQeFS3wi7TXjGqTnynRmAB1pQAbDQDrrgFURQC4
+gPYIC/HcAHipYDdUwI2vBywJ3z0RuUCvthctdictNjcA2A60+bF06yXK0Uh8gyNgpTr1a+PYR5o
YD3IQQkiCEF1BmorgESkBzWo3jb0/0mvzp33ckgmkUdqUtP0oiD0d6AWhWRqiWy9mhSLwnVKT7HI
SyLxpvqZzl1KTB5A9WaKLkzI/pUV4G9ud9tQ9PDCzAAABr1JREFUWEftl2lUVVUUx4/PKecKTSBk
EKdEcwAH0jAmkUHApS/qIYqEBg4ouoCYBHzkAxYgggkRiTikPpWCBOSBPB7wHuBIJeWQpknOVGof
W+vfPnAIwScWX/rSf60f796z9757n33uuffC/tf/0quAhhQWoHvCAuqhl1W6P9lKXZbw7iqpchCT
Ng8QZ72Qr2bq1LgmVP/8B4p/fIzjVx51oZDgtmHBVIhUOVREtctf6z8kSIeBa3RgKzQbxWgvtLwq
xT2zGfsv/oascw+RebaT3edbsedcK9hKTbPwbtcK9UcmmxtRdvkRTl1/jEU7LlIRNbvZijpT4fEv
JFUtGOCvRmrdXew8/QDpjZ3knH+IxPIWMFllvvCmrlVMtY47i9qbT1B14wnKqYDaW38gSXWr3U92
arbw/AeSlhj29VUhubIFuZQsreE+Uus7+YzGVhdcoguf7GyxVPnqqCA1ogqvo5KSn7j6CEXUCdW1
x8iuvQPmU5ZPPqOE9wvkU5IReuQKcqn1Kdq7SNXdQ2bjfaTX30MSdeRzKsA2roHWv2y+iGgXFcF8
vk4xXa/GF+cfoOjS71A2/4YSumeiv7xGRZRkCM8e5Fm4yGpLNa3xAyTV3EFy3R18dvY+XFPOIIuS
p1Mxey88xFDf0mdvwA55F/sPlpVgl6YFyou/Yl9TK4p++B2zouvAlhavEV7PkaeySFF2AymUXK6+
jWyauX28Fsz7WJpFcDnyqZhc3V0wz6OXRIR+eRY6D1hWiPzGu8inTubThPadvgfmdfSC8NCjhUoL
s8CvkdN4D7GqFiRrbmPTwWYw90Pt+93jgOKtKDVij10GW3zo07axnuR+eI3FmhM4QEuWRUu5n36d
ttWCuexfJDy6ya1go1/maSSpf0Fk6U3sqruN4csO84BxwoOK3OPwyrtHwJxzp4uRnuVSsC/hqyvY
WXsbmbScHxdfBXMtOCis3eSUVxR3/DJiKDkn4tD3oITPOrvkvSqOXizHHGe7iHJkUQFy2pK71LQt
nfOuCms32WdfUpRcRyhtpXgqwPtjNegCHwhr70TFvuy1F5maXxBe9BOyqavMIQfC2k1vZ7YmnbyB
4MNXEV9yEzZrj4PGFghr72SbPuglp2yknbqFDcofsaOqBcNcc8GcPh0hPJ6SbVqr164mGEfoYJd2
AcZL94DNT7UW1t5pXsbEkYtz8U56E14L08Jz93eQzEvnW7iv8HhKsxXNnqmNMAnXYa7iHMbLCsBs
Fc+5Y/VI30XnJgXPXnsMM+Vn8Hq4Fl47zoDNUTznHpiZULhYXoXxkTpMiW3A/JBCMOvEj4S1Z1Fy
iU1iu791Umd7reW17ttrYEaznxBVD+eoMvKR7xbWbpoW7WPluwc28Q0wCa2BW2IN2LStjcLas6Zv
dR8vzcX89UdBx+0JpseEWSzJhq38NAzWqem3EZNln4PNiF/WZn9GttJB/WbEwIMeu6MpYC4VYuax
E2xq5Gbh8XxZhac4bf4S0qwmTJHlgVlFZAyYuRVu27Uw3lANQ3o/eCbXo8+bUbT+Uj3rLyR5Y0uK
Y8hRTA6rg/H6arjJa9FvSjjYG6FLhIt+TQr71jVBA/ONGizY1gBz9ww4RJyEJXVyRGAlZkTpYO1H
s58Q9oIlHbvRtL/VFnjIa2AcXIWxIdVwjToJPsYsN/kLr66imBGzYmCX0IAhK1UwoIQWFMfjh/mr
YLJWDY+4U5BM2kT7v4fZ/61xwZtN7BPhmFAPw9WVsNygxsJIuhCNsXHrVMwyqGs3xq4LtpHlYHKo
BgNlZV0YGVABlwQtRs6J4bF+IuLFkph/mGHhmAiHrVqM/qAChoEVsIuth2xbOYa/Sd0wCHpduDKJ
WdBBx5DjMKKZ9/cp7YI5dWHMO9sgMQ1SCPd/LsmYgDSTebFwjavB5BA17GN1eMuPnmKmgU+to7Sv
xCwQzrE1GPp+KfotO9EFw1UqONB25j7MzM9CBOlVHwFfo/7EQGKQxMhXMWRCMDw2KWFpnwCJkU8e
G2jF346GbYx28hozLxqBn3yDBdFa2HWDFx1AT1eH1XshMZSliWvzHB352tRxwo1DiJGEOTGFmMMG
Twtio7xVbOjMODr3JpYSUuI94n1m4FbRx2g5ekIy2vsIe2kGf6+8RvAvKZ5LQrQVwf/wEz7IjdzJ
kuDvfP7d50J4EjyxDyEjlhN8V6wS8OMVBLfxwvjDxotwJXhiG2IiwTs3jOD/uPxdQIf4QD+Ct38w
MZzg737+NcsDjQkTgn/nmxG8S3xdO+Dn3MZ9+E1qRPDJGBAvE7y7/No8R5fE/6EY+wv1r6tSMwqn
vwAAAABJRU5ErkJggg==')
	#endregion
	$buttonstartMissingToons.ImageAlign = 'TopCenter'
	$buttonstartMissingToons.Location = '103, 7'
	$buttonstartMissingToons.Name = 'buttonstartMissingToons'
	$buttonstartMissingToons.Size = '88, 81'
	$buttonstartMissingToons.TabIndex = 11
	$buttonstartMissingToons.Text = 'Restart Missing Toons'
	$buttonstartMissingToons.TextAlign = 'BottomCenter'
	$tooltip1.SetToolTip($buttonstartMissingToons, 'Checks for any toons not running and starts them')
	$buttonstartMissingToons.UseCompatibleTextRendering = $True
	$buttonstartMissingToons.UseVisualStyleBackColor = $True
	$buttonstartMissingToons.add_Click($buttonstartMissingToons_Click)
	#
	# tabpage2
	#
	$tabpage2.Controls.Add($combobox1)
	$tabpage2.Controls.Add($buttonTaskbarGroupingFix)
	$tabpage2.Controls.Add($buttonEQClientiniReadOnly)
	$tabpage2.BackColor = 'Transparent'
	$tabpage2.Location = '4, 22'
	$tabpage2.Name = 'tabpage2'
	$tabpage2.Padding = '3, 3, 3, 3'
	$tabpage2.Size = '291, 259'
	$tabpage2.TabIndex = 1
	$tabpage2.Text = 'Tweaks'
	#
	# combobox1
	#
	$combobox1.BackColor = 'Info'
	$combobox1.DropDownStyle = 'DropDownList'
	$combobox1.FormattingEnabled = $True
	$combobox1.Location = '6, 145'
	$combobox1.Name = 'combobox1'
	$combobox1.Size = '278, 21'
	$combobox1.TabIndex = 15
	$combobox1.add_SelectedIndexChanged($combobox1_SelectedIndexChanged)
	$combobox1.add_Click($combobox1_Click)
	#
	# buttonTaskbarGroupingFix
	#
	#region Binary Data
	$buttonTaskbarGroupingFix.Image = [System.Convert]::FromBase64String('
iVBORw0KGgoAAAANSUhEUgAAAC0AAAAtCAYAAAA6GuKaAAAABGdBTUEAALGPC/xhBQAAAAlwSFlz
AAAXEQAAFxEByibzPwAACmBJREFUaEPVmYlXU3cWx2Npq45z3LWordUO4AIoq0IUkM0y4qgdtRYR
EGXRCmMdtXYURCEQEkKIEGRVdpGwg+xuoGNHsSKCyqq4VOTMOfZP+M79PV+YBKjCyEHnnvM9L+93
3zOf3Hd/996HgjG2cfzx/8M+joiynJqQrBKEiL/ilz5wCxGZGKgK7mxrudepp1JdFBw89iXv+UAt
NNRULy+/yauz7a7/00c3PDra7umdz7v04YIHhZoa8MC+Pd0/737c9S92HAb4e8p9kdREX6W6owms
lu8TDfBjYVrgOhKZ45TTSSW0/id+aYzs4MFJM1PP3PbsaGsZCKyWH63vaH/wcGZySil/l0BwMtx+
SWHR/W2tLR0Lcs41CI4cWcB7xsY+ilZsN6uo6PLreXRrKGiK9m3zysoWHZnCkbuBgBcXFj7Y9ajr
F/+nPTfc2x62vBdwgVi63fTCAHCKsO/j18CCcIk9dx0DLngN3J/7lELubfdbFmSfuzb24BKZm2l5
ebcPgTMgHwI20wSm40Bgtdh5f8RDxO8h4pQqBNGkFeHAwMlzMjKbd3V3DtqsarFUYTk+NTGpiLtn
LG2CTO7+RVZ2y3i53IFf4myCIu4764sX24fKffZDvLs7m4yKS24JJBIz/pYxNGCcYP/+qfyZln0i
idlmXVfXoQnOgOkJNC0tKm5k9Z6/dJgWFWWkI45y1ZFGu2hqPK+B62oN6YuUOas/M/+nkuh19O/P
Zl/ziUy2jYv4k56bXKo86rqztKho5MCTZDJnS1n0K1e5HH+Oju7XOpIzaVG0HE78uabflWRPMiD/
13Rkfk0xvwNpqiIOAql8I/91HLiQwGlTNv9vEY6Qrv1CEfvKTqmE7alT/bLjpSePgani9eeBfpvY
WMxn/hgFVikUENJRGBMDIa0JKQCr6PNXsmgsF4VjqljcD81scqzS7YuMrJsCsXikEVY4WyUl/bYh
LQ3rUlP65UpyTknGImU8d1yv4VP77VNSoCuKwESpDHqxSuglJEI/9Qz00zNgkHMOS/LzMS8nF5Zh
IriEhGCiWKoFLQgJ+Ujw00/T+LNhWph07VxlwivbtHSsTk3tlw3J9uxZLFSextLTCRAmJ8MqiSmp
X9Z0zTKKntDbG7qSKGyPV2JHeho88lXwqq6Ed0M9/O42weWf17E6LAxfnzgxGHqkw9IkRZyz8Ny5
3zYVF8OVvkit9SRnlYoeuQLzCXo5Rcz4fB6MC4uwrKwcy8ovwKSiErMysmC893s4eezALLEEWyWR
2KaMw3dpZ7E9Pw87Ki5w4E61tVg1BPT46FMuUxKSsijaM/mlt1iY2GlWfOIrq/PnsTI7W0vWubmw
SEiA848/wunMGfjW1cDnegN879yGX9sD+Pc8wr7nT2FeUwvDPXvh6OmBWeFibA4O5sC/VYOr8uBV
VQHHstLB0GFSJ/PKqpYt9+52zUvPLBHsfVuKbP3+j7oZWd2WFy9RxCq0ZFZVRRHMhMXRY9hy6BDs
KEe9iwuxs4oed/1V7Gq8id33Wzlw06pqHtoTs0JF+Obg37H5eDC2aIB7FOTDnuAZtMuJEPwhQrJO
EC5dRcNVK5tJWAfc2nrvwVwGvvvAdJ5wCNu+fZpxWXlfwMtfsedZj5YCe5/DjB6n+T+OYfPhw7Cj
yuCVnQXPwgIuT3cSuHfjLYr4Q5hWVvVDzwwJxUZ//0Hg7pTjazIyYEPQa44fxzix9JRFdVUjm/rU
jYUDb2l++GZwgjYsKe3bQ4+YBhotMXCT6mqYU6QZtC2VKk/ahB4MvEgNfoVLFRPKb0OW014EHXQc
G93c8I2vL/76ww/YEnQM34oj4K6MhQNtWqPwCMyNiMSy0rJevyePb7LpTw3N5Pfk0c8ceEZWseDA
UOAjgLYRi+GhiMGO5CQtcJbjJoWFtBH3wt7DA9Mpp60D/wbhocNYFRTEVQtbqRSOVPeX0NPSJf+S
rGx4d3e0+fR039AEVmsPRXzD7caeibHKFJ5Uw4YJvYU2ot3Jk/AKF8GTwL0IfCeBsxz3o81plnse
evsCsDI+Hm4dbdjR1Qn3zg5SO9w72um8A5Z1FzGXOqV9WCgsxJGwra9/tufZk0HQ3CtZ+8Pmhbl5
jdRolvOkGjYMaAvK6U0Uab0T9GUnSZGRsKQOZ0mRW0HpIszMxPzEZEyQxcDq8mU4XLuGNVTe1tS/
ln1DA1bU1sGQGtM6ObVxEVWPo0cxURZT4Xj9eqv/08f/BaZU8aR3y4Xncm9TKzfmKQeYK23E0rK+
gF7aiE9pA2oo8MVzKmU1MKRIO56Kg09FFXxJPhfUqoQfHd2KyzBZfgqz4xNgRNVmSXYOluapQEMP
qRhGJSWYkpAMe0qN9dTG7Sld1lLJ+1Qk+svEGKU//cAu2oCvgTva7i54IzAzqokzU8/2mVHJMmGN
QkNm1DQ+S8vA9Cg53ApLsI8A95ZXamlfBaVPUipM6YdZUdf0v1jL5bhf0y/wb38I/ydUx188wyKC
X02ziCa0uk5TY9vv0NDQ5dnZfu/NEVYb9fppyal9S0tKsZi6nKZYlGaknMHsM2n0I8phXFqqpeXl
ZfiMOqERVYsNlD4WiUnYxep4fzlkdbyFq+MGBUWwoSFLDc3qtGZHnJKQcEA3Lf2OICR8Gb/0BlOn
R9/v1GlqMssJOODXZ4PSJ4AiaHX5CoyPBWM9bVTzOCV25mRTVSnUquMs4gb5hf3QjgRtTUOT5mhK
7ftjCuAM/uwt9raNSGlC9ZSDHOSntRWXLvHQR2BOm5NVFY/szNcNiDqnuo7r5+bBhkbXjTFyGEWI
sZg0xMA0TBst6CNHYCaRcuVQq44TOMtxfdqcbN5eTZFmzUUzp0duowS9gaDNQ8Owk8qZJ0XTMykR
XlmZ8CZwVscX0UytTy8EhlSnHVnJe9/Qy44GwSYoGF/S8G8RKYE5gVnExtF0mAjLlFRYUxmcFnca
hpTTrhRphwHVY+Q2jI3IKgfbdAP9Ab3PILx8CXNEYuwqKsHJqw0IvlKP4MtXEcTr+KWrcM0rgH78
abhQt3SlpzCw5I3cqE5TWetjw7wRlT1NsSF/FpU7quNctAf5aU2XHruukubtnPNwzM7VkhNpdWYO
VtCb0MbMDKylt5lRgt47bU5aep+Q2q8VjaGaordjzMvMwpz0TO7zUP75tME+JwkpTVbW1WnJmtZm
0A92oDa/ifLbWQPaZVTS43fa+FvrNMFb0CwdQNcO8tM9BgWFsE1P14JmG3G1iNXpaBeeYoT2rhuR
Bir2w9i1Q/n18wtgRymkht5A0MZRMkyRSOMEKpUOTzFCG0NothHt4+KgI5W9AzCzMYFOx2ZqNiZU
AqfI5O8IzGwMoO1pIzrTTKIjJeCtW98RmBlBG1+o6Av490vsYZtNQ4F9vTAjqOWVlQh4+WKQP6Dv
BayoQljU1NLn3sF+umcxlcYlZ9MwTRGrHB1gZoGBk3XPZlxZWVPTalld3awpq9qaZvaHb920jGar
mhotH+entc+zspvpBZS7dpCf1qjGPxBEymTcFDeqxv6GJhAMrTf51Hr7/aP0f4MCwX8AgFiMVCEi
5poAAAAASUVORK5CYII=')
	#endregion
	$buttonTaskbarGroupingFix.ImageAlign = 'TopCenter'
	$buttonTaskbarGroupingFix.Location = '6, 6'
	$buttonTaskbarGroupingFix.Name = 'buttonTaskbarGroupingFix'
	$buttonTaskbarGroupingFix.Size = '88, 81'
	$buttonTaskbarGroupingFix.TabIndex = 12
	$buttonTaskbarGroupingFix.Text = 'Taskbar Grouping Fix'
	$buttonTaskbarGroupingFix.TextAlign = 'BottomCenter'
	$tooltip1.SetToolTip($buttonTaskbarGroupingFix, 'Turns off taskbar grouping.  Allows independent movement of each window on the taskbar.
Modifies the registry - Must be an administrator.  ')
	$buttonTaskbarGroupingFix.UseCompatibleTextRendering = $True
	$buttonTaskbarGroupingFix.UseVisualStyleBackColor = $True
	$buttonTaskbarGroupingFix.add_Click($buttonTaskbarGroupingFix_Click)
	#
	# buttonEQClientiniReadOnly
	#
	#region Binary Data
	$buttonEQClientiniReadOnly.Image = [System.Convert]::FromBase64String('
iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABGdBTUEAALlrZELNbAAAACBjSFJN
AACHCgAAjCAAAP5TAACDgAAAfvwAAOlWAAA+EQAAIt5KhyhXAAAE1WlDQ1BJQ0MgUHJvZmlsZQAA
SMfllntMFEccx3+79wYO7uA8pDw8KUWkB70CSk8I4VGkIAICglhy5V7CCXdslgNBWoFCCr7wAVVp
aFGCgpLWBsUixfqiQiChiClSrCKexgcPFQsJD73Oco0kNTXp33yTyXzmtzO/2Znd784CsM/KCSID
BwCtTk/GhgWLNiVtFrH6gQlsEIAN2MiVWURQTEwk/Kem+gGj6hseVK7GyLXquy131joPK3aOnfdQ
wdvFJdGEAJgIsSDVxD4UK0z8CcXb9IQecTLFyjQ5yokRiMVkfGwI4mrEc6nzjB+hWDHPtEqKc5Sp
aCx9P2KJTqXRIb6Erlmq1FlKAFYviu9SEiTqw6bye2i1mSg/ew9iN2ovTLeZWQIgPYnyOy7EUlD5
MRVA+HQhtiIWtW0BWoULsRfL5vcH++inrC3eXvMhjN+K5nAxGserAMzKAV6uMRpn+EbjXB8AQwzQ
6KTMJnP+2aNcVGhgBrawEoJABkVwCgYxPhaNVWLDuC9+CH9FI2ijdJJBZxxjhjNfsS6y93DUZhHm
/hZruCGWiVY5vFr+mM0mwV1h0dLVdtP27Y77lsUspzu3ueS7BrtZrbz//mWPEx9UfFjmXbqq3Peo
tM3PECAMTAiu/Xg2LCW8LzI6amCDNt4ioTlJk+wqG5W3qvanZmyN1voSLlmCHFbuXP7zHQ+KbpZ0
lrbsath7ZH9ZRf4hokpTvaVGU0seL274rrH9h8kmn+biFkPbxou3r2Z3CLuu9OT1+fdz/xi9PTg8
8ODRE/PxoIm9U89m043GN9ZuAfYggXWgha+hHaax1dh27Bpuh+vxAVoorZUupV9mxDGeMg+x1rIx
dgfnsBlpnmgRxg2yDLWK5Wn45dbtAvMlCmHX0iC7TnuZI+Z0RkQ4+7vYumIrZtxBLPD0lsi8Knyu
+wqlCr+mAHrgpuCzoY5hFRFLImuj/TYMxe9NDN3MSO757FtFljoqzTOdp50kBrN+yTmWV/h5UoG4
aKrkXKl2l8OeX/elHWRV1h0OrLpTvaPG5dj1utL6iFMO38Pp6TOcc6vOF7SNXipod+sY6q7/rfRG
8c2aW4a7cfcnH/eOj/wVOT37xtpx4CAfvgu+EAM6OAg/wxNMhCVjR7ERPACvwl/S0mkGuor+nFHG
dGcOsA6wEzluZgyzcfN7FsPcUSvgOfJjresFdkvqbdfbsd7pdahzyhdFO7u7WLuy3DjutmKJZ5yk
0KvZ57mvtzTP70oAFz33E6EQpkLPPSKqa0N83MOEL5Pe+7RXViz3V85tuaIpz5BlepNc/eNtndtP
frG7UFcc9ZX7TvruW+VNB8oqUw5Lv7Gtnqkx1P5+vLdhoHHstHVTeHNly1QbeYlz9WzH1m6PHmOf
of/PwZEhgSHp4YXR0GcTk50z3Uajyasmh5i+KZQeFS3wi7TXjGqTnynRmAB1pQAbDQDrrgFURQC4
+gPYIC/HcAHipYDdUwI2vBywJ3z0RuUCvthctdictNjcA2A60+bF06yXK0Uh8gyNgpTr1a+PYR5o
YD3IQQkiCEF1BmorgESkBzWo3jb0/0mvzp33ckgmkUdqUtP0oiD0d6AWhWRqiWy9mhSLwnVKT7HI
SyLxpvqZzl1KTB5A9WaKLkzI/pUV4G9ud9tQ9PDCzAAABztJREFUWEfVl3tQU3cWxxFf23en9kF1
sbUP7Y7dVrvV3XV9dNtpLbWt67q23Tq13e2uM87soGu7WNctAVFqBR88FhKQACkpDyGEl1CUqpAA
NpEAAZIQloA8I5iAISE31853z+96abWaEbf+s9+Zz9zc3znne87v3l94BPzfqaioaE1xcbGipKSk
s7S0FAz6zNFaFcW25uXl3Smm3lpRgw8JfV1tLTo7O+F0ODAhj9uN/r4+NDY2oqysDGq1OlwsuzVS
qVQHTpw4ITQbHRkRGB4aEpr29fbivN0uDMTWmTQaDQoKChLE8h8nan64urpaMLYPDqK7q0tokCKT
YXdkJMLDwxEbE4NClQpmkwmDAwNCrlarBasVbf430fvcUl5eLhh22WxobWlBulyObdu2QSKRID4+
HocPHcLu3bsRGhoqrGlqamCjV8TEapmHaHdzosKpBAwNDTC1tcHa3g55WhrCwsKQmZmJ3NxcFcXZ
oduVnZ2tpPveuLg4/GvXLpw7d06oYbXMg3mJtpNXVlbW23S6cfbsWej1elRVVSEqKgpKpZLxgZh2
lahmf1JSEioqKqDT6YRaOrigAdeJKZMX7VJZSydeS++bHbRkMlYoFIzlYsp1RXFZdHQ0WoxGoZY9
OeYlhievjIwMax+dcnb62ZXtLD09fbsY9is2YEJCAkx0IFmtjc4O8xLDk1daWprnEs/jGH2vh+gr
l5qaCrlc/oAY9iuWI5VK0U47Z7VOpxNHjhwZEcOTV2pKinCSi9RqXLp0SfjaTeYwUc4Mlsue2kQt
8xLDk5c0OVkYQF1YKFzZvRi6oX5MrSCZTHYPO3RMEyb/TkyctAnLZZqoZV7MUwxfK8qZQgQSU4mZ
LfHPJRjjnoc56VewHnkJnco/oFu1GX0VO2GvOYBhvRyOplw4W1RwGo/iQoMC52sTMFAViZ7iUNhy
3kVHeggs0uUwxS+G7vAKNMcv3UHe08U+rN8Usf13AzCmNu9bENaR8hK4Pj243jqMt2YJeNtV4Gzl
8PWchq+/Hry9Afz5JsIAflAHX68GXNdxeDuK4DXnYNwoh8eYCa6nDp6OE2hPXonmzx5lQ1zdnOnK
AXRRj3QMqTaB666ixnK4qjbC/fUf4dFuwbjuE3ib9oFrSwBnSYPPmgGunTAlw2s8AO/ZcIzXbYWn
+n2MHf89XF9tII80wWtY/SfoI+faqIfwBMTW30scILBWEozR8j/TbkrAmVPIbAO8mt+B09FQhr/B
Z9wJn2kPeEsM+PaDxAG6j4av9VP4GreB038Irv4tjJ9+DZ7TVEfDcbYijJRtQm34HGpxgwFO7ZyD
0cr3aIBC2l0ivHVrwJ15Gb6GtfA1bQTfshm8aSt48z9oiB2XMW8H37oFfPP78BnWw6d/FVzdKni1
q8mDnlZXAUYq3sXJT4LYANe+AqaJQOXHQRg5vpEeWz4462GM178I75lfwpz7HMxHl8GS/wIsqldg
KaRDpl5zmcJXYSl4Eeb8FTDnLYE55xl4639Br2MVeRyiAfLgrHwblR89JAwgtrxWLFgS+gAcX70D
b9dROngH4dYup/f/LPieJPC9KeD70sD3ZxAK4guRTFqXUzyV8pLBn0uER/M03JplGKdX5LXlwlGx
AcWh9994gPwt92H42FvwdObBY4rB6KkluHhyPlzVC+GqWYQx7RKM1f4aY3W/IZYTK+h+Ga0vhUuz
mPJ+Dtfpp3Dx6ycxcvJ5uMnD858cDJWuB/MWW/mX8i/3wl60Hu6OHLiM+2jyZ+EoD0ajdDYaZXPR
mPIIMQ9NqY8TT4g8RmuPXo7L5lBuEBzHgnGh/Bny+Bxuazbs6nVg3mIb/5K/dxf689dhzJKNUUM0
FT6N86qH4W7bR5CZab+wK7cp9grYPa2zuJD3GewFQbSRhYKHy6wkz7Vg3mIb/5K+cwd6stfC1fol
nN/sQX/OfPRlzUL/l/djIPtB4iEM5DCCfgCtUYzlMYSanAVw6vbiYquSPN8A8xbb+Ffc+tvQlfkm
RpqzcEEbhW7547BJ70KN5E7URND1CjQRdxP3CHy3zvIIm/RudKc/IXgwL1vG62DeYhv/inlzJqyp
r8PR8AXspyJhTZwHS+ztGNJIvkcb4R8xxxJ7B9U+Jng46HeFVbYGzFts4197Q6bDnPgahnUK9FdK
0Pp5MJolM2CMnHlTNEfMRNv+ueg/TkN9kwlTQgiYt9jmKgUSMwj2L9WsiJenwXgwBPY6BXpKw2H4
dA5026dB99F1+Hj69T8LTIch/KfkIYG9NgPNsavBvKnHvcRtBPvjRviZ8BPiQWIh8cI/VwXyhj2r
MVijQJdKgvq/z4bmr4HQbr45NJun4sz22YLHYHUGDHtfwa7fBn5LPZYS8wj298E0QpjmYWIxEbJp
UcCxsJUB/I6VU3BLWRHw7QeLAsqox0piPsGehDAAexS3E7OIYOJJYgHxFPEz8XorYE3Zztlm2e7p
tQcE/he1KvPnPfHWFAAAAABJRU5ErkJggg==')
	#endregion
	$buttonEQClientiniReadOnly.ImageAlign = 'TopCenter'
	$buttonEQClientiniReadOnly.Location = '6, 172'
	$buttonEQClientiniReadOnly.Name = 'buttonEQClientiniReadOnly'
	$buttonEQClientiniReadOnly.Size = '88, 81'
	$buttonEQClientiniReadOnly.TabIndex = 14
	$buttonEQClientiniReadOnly.Text = 'EQClient.ini ReadOnly Toggle'
	$buttonEQClientiniReadOnly.TextAlign = 'BottomCenter'
	$buttonEQClientiniReadOnly.UseCompatibleTextRendering = $True
	$buttonEQClientiniReadOnly.UseVisualStyleBackColor = $True
	$buttonEQClientiniReadOnly.add_Click($buttonEQClientiniReadOnly_Click)
	#
	# CPU
	#
	$CPU.Controls.Add($labelLogicalProcessors)
	$CPU.Controls.Add($labelCores)
	$CPU.Controls.Add($labelCPUName)
	$CPU.Location = '347, 294'
	$CPU.Name = 'CPU'
	$CPU.Size = '299, 80'
	$CPU.TabIndex = 20
	$CPU.TabStop = $False
	$CPU.UseCompatibleTextRendering = $True
	#
	# labelLogicalProcessors
	#
	$labelLogicalProcessors.AutoSize = $True
	$labelLogicalProcessors.Location = '7, 54'
	$labelLogicalProcessors.Name = 'labelLogicalProcessors'
	$labelLogicalProcessors.Size = '100, 17'
	$labelLogicalProcessors.TabIndex = 2
	$labelLogicalProcessors.Text = 'Logical Processors'
	$labelLogicalProcessors.UseCompatibleTextRendering = $True
	#
	# labelCores
	#
	$labelCores.AutoSize = $True
	$labelCores.Location = '7, 37'
	$labelCores.Name = 'labelCores'
	$labelCores.Size = '34, 17'
	$labelCores.TabIndex = 1
	$labelCores.Text = 'Cores'
	$labelCores.UseCompatibleTextRendering = $True
	#
	# labelCPUName
	#
	$labelCPUName.AutoSize = $True
	$labelCPUName.Location = '6, 16'
	$labelCPUName.Name = 'labelCPUName'
	$labelCPUName.Size = '61, 17'
	$labelCPUName.TabIndex = 0
	$labelCPUName.Text = 'CPU Name'
	$labelCPUName.UseCompatibleTextRendering = $True
	#
	# folderbrowserdialog1
	#
	#
	# openfiledialog1
	#
	$openfiledialog1.DefaultExt = 'txt'
	$openfiledialog1.Filter = 'Text File (.txt)|*.txt|All Files|*.*'
	$openfiledialog1.ShowHelp = $True
	#
	# openfiledialog2
	#
	$openfiledialog2.DefaultExt = 'txt'
	$openfiledialog2.Filter = 'Text File (.txt)|*.txt|All Files|*.*'
	$openfiledialog2.ShowHelp = $True
	#
	# openfiledialog3
	#
	$openfiledialog3.DefaultExt = 'txt'
	$openfiledialog3.Filter = 'Text File (.txt)|*.txt|All Files|*.*'
	$openfiledialog3.ShowHelp = $True
	#
	# openfiledialog4
	#
	$openfiledialog4.DefaultExt = 'txt'
	$openfiledialog4.Filter = 'Text File (.txt)|*.txt|All Files|*.*'
	$openfiledialog4.ShowHelp = $True
	#
	# tooltip1
	#
	#
	# folderbrowserdialog2
	#
	#
	# folderbrowserdialog3
	#
	#
	# savefiledialog1
	#
	#
	# folderbrowserdialog4
	#
	#
	# helpToolStripMenuItem
	#
	[void]$helpToolStripMenuItem.DropDownItems.Add($aboutToolStripMenuItem)
	$helpToolStripMenuItem.Name = 'helpToolStripMenuItem'
	$helpToolStripMenuItem.Size = '44, 20'
	$helpToolStripMenuItem.Text = 'Help'
	#
	# aboutToolStripMenuItem
	#
	$aboutToolStripMenuItem.Name = 'aboutToolStripMenuItem'
	$aboutToolStripMenuItem.Size = '107, 22'
	$aboutToolStripMenuItem.Text = 'About'
	$aboutToolStripMenuItem.add_Click($aboutToolStripMenuItem_Click)
	$CPU.ResumeLayout()
	$tabpage2.ResumeLayout()
	$tabpage1.ResumeLayout()
	$tabcontrol1.ResumeLayout()
	$groupbox1.ResumeLayout()
	$menustrip1.ResumeLayout()
	$MainForm.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $MainForm.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$MainForm.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$MainForm.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$MainForm.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $MainForm.ShowDialog()

}
#endregion Source: MainForm.psf

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	
	#Sample function that provides the location of the script
	function Get-ScriptDirectory
	{
	<#
		.SYNOPSIS
			Get-ScriptDirectory returns the proper location of the script.
	
		.OUTPUTS
			System.String
		
		.NOTES
			Returns the correct path within a packaged executable.
	#>
		[OutputType([string])]
		param ()
		if ($null -ne $hostinvocation)
		{
			Split-Path $hostinvocation.MyCommand.path
		}
		else
		{
			Split-Path $script:MyInvocation.MyCommand.Path
		}
	}
	
	#Sample variable that provides the location of the script
	[string]$ScriptDirectory = Get-ScriptDirectory
	
	#region buttonup
	function buttonup
	{
		$this.Cursor = 'Default'
		$this.Enabled = $true
	}
	#endregion buttonup
	
	#region buttondown
	function buttondown
	{
		$this.Cursor = 'WaitCursor'
		$this.Enabled = $false
	}
	#endregion buttondown
	
	#region Update-Display
	function Global:Update-Display
	{
		param ($ResultToDisplay,
			$color = '238, 237, 240')
		
		$ResultToDisplay = ($ResultToDisplay | Out-String).replace($null, " ")
		
		$richtextbox1.SelectionColor = $color
		$richtextbox1.appendText($ResultToDisplay)
		#$richtextbox_output.appendText("`n")
	}
	#endregion Update-Display
	
	#region Get-IniContent
	function Get-IniContent ($filePath)
	{
		$ini = @{ }
		switch -regex -file $FilePath
		{
			"^\[(.+)\]" # Section
			{
				$section = $matches[1]
				$ini[$section] = @{ }
				$CommentCount = 0
			}
			"^(;.*)$" # Comment
			{
				$value = $matches[1]
				$CommentCount = $CommentCount + 1
				$name = "Comment" + $CommentCount
				$ini[$section][$name] = $value
			}
			"(.+?)\s*=(.*)" # Key
			{
				$name, $value = $matches[1 .. 2]
				$ini[$section][$name] = $value
			}
		}
		return $ini
	}
	#endregion Get-IniContent
	
	#region Out-IniFile
	Function Out-IniFile
	{
	    <#  
	    .Synopsis  
	        Write hash content to INI file  
	          
	    .Description  
	        Write hash content to INI file  
	          
	    .Notes  
	        Author        : Oliver Lipkau <oliver@lipkau.net>  
	        Blog        : http://oliver.lipkau.net/blog/  
	        Source        : https://github.com/lipkau/PsIni 
	                      http://gallery.technet.microsoft.com/scriptcenter/ea40c1ef-c856-434b-b8fb-ebd7a76e8d91 
	        Version        : 1.0 - 2010/03/12 - Initial release  
	                      1.1 - 2012/04/19 - Bugfix/Added example to help (Thx Ingmar Verheij)  
	                      1.2 - 2014/12/11 - Improved handling for missing output file (Thx SLDR) 
	          
	        #Requires -Version 2.0  
	          
	    .Inputs  
	        System.String  
	        System.Collections.Hashtable  
	          
	    .Outputs  
	        System.IO.FileSystemInfo  
	          
	    .Parameter Append  
	        Adds the output to the end of an existing file, instead of replacing the file contents.  
	          
	    .Parameter InputObject  
	        Specifies the Hashtable to be written to the file. Enter a variable that contains the objects or type a command or expression that gets the objects.  
	  
	    .Parameter FilePath  
	        Specifies the path to the output file.  
	       
	     .Parameter Encoding  
	        Specifies the type of character encoding used in the file. Valid values are "Unicode", "UTF7",  
	         "UTF8", "UTF32", "ASCII", "BigEndianUnicode", "Default", and "OEM". "Unicode" is the default.  
	          
	        "Default" uses the encoding of the system's current ANSI code page.   
	          
	        "OEM" uses the current original equipment manufacturer code page identifier for the operating   
	        system.  
	       
	     .Parameter Force  
	        Allows the cmdlet to overwrite an existing read-only file. Even using the Force parameter, the cmdlet cannot override security restrictions.  
	          
	     .Parameter PassThru  
	        Passes an object representing the location to the pipeline. By default, this cmdlet does not generate any output.  
	                  
	    .Example  
	        Out-IniFile $IniVar "C:\myinifile.ini"  
	        -----------  
	        Description  
	        Saves the content of the $IniVar Hashtable to the INI File c:\myinifile.ini  
	          
	    .Example  
	        $IniVar | Out-IniFile "C:\myinifile.ini" -Force  
	        -----------  
	        Description  
	        Saves the content of the $IniVar Hashtable to the INI File c:\myinifile.ini and overwrites the file if it is already present  
	          
	    .Example  
	        $file = Out-IniFile $IniVar "C:\myinifile.ini" -PassThru  
	        -----------  
	        Description  
	        Saves the content of the $IniVar Hashtable to the INI File c:\myinifile.ini and saves the file into $file  
	  
	    .Example  
	        $Category1 = @{"Key1"="Value1";"Key2"="Value2"}  
	    $Category2 = @{"Key1"="Value1";"Key2"="Value2"}  
	    $NewINIContent = @{"Category1"=$Category1;"Category2"=$Category2}  
	    Out-IniFile -InputObject $NewINIContent -FilePath "C:\MyNewFile.INI"  
	        -----------  
	        Description  
	        Creating a custom Hashtable and saving it to C:\MyNewFile.INI  
	    .Link  
	        Get-IniContent  
	    #>	
		
		[CmdletBinding()]
		Param (
			[switch]$Append,
			[ValidateSet("Unicode", "UTF7", "UTF8", "UTF32", "ASCII", "BigEndianUnicode", "Default", "OEM")]
			[Parameter()]
			[string]$Encoding = "Unicode",
			[ValidateNotNullOrEmpty()]
			[ValidatePattern('^([a-zA-Z]\:)?.+\.ini$')]
			[Parameter(Mandatory = $True)]
			[string]$FilePath,
			[switch]$Force,
			[ValidateNotNullOrEmpty()]
			[Parameter(ValueFromPipeline = $True, Mandatory = $True)]
			[Hashtable]$InputObject,
			[switch]$Passthru
		)
		
		Begin
		{ Write-Verbose "$($MyInvocation.MyCommand.Name):: Function started" }
		
		Process
		{
			Write-Verbose "$($MyInvocation.MyCommand.Name):: Writing to file: $Filepath"
			
			if ($append) { $outfile = Get-Item $FilePath }
			else { $outFile = New-Item -ItemType file -Path $Filepath -Force:$Force }
			if (!($outFile)) { Throw "Could not create File" }
			foreach ($i in $InputObject.keys)
			{
				if (!($($InputObject[$i].GetType().Name) -eq "Hashtable"))
				{
					#No Sections  
					Write-Verbose "$($MyInvocation.MyCommand.Name):: Writing key: $i"
					Add-Content -Path $outFile -Value "$i=$($InputObject[$i])" -Encoding $Encoding
				}
				else
				{
					#Sections  
					Write-Verbose "$($MyInvocation.MyCommand.Name):: Writing Section: [$i]"
					Add-Content -Path $outFile -Value "[$i]" -Encoding $Encoding
					Foreach ($j in $($InputObject[$i].keys | Sort-Object))
					{
						if ($j -match "^Comment[\d]+")
						{
							Write-Verbose "$($MyInvocation.MyCommand.Name):: Writing comment: $j"
							Add-Content -Path $outFile -Value "$($InputObject[$i][$j])" -Encoding $Encoding
						}
						else
						{
							Write-Verbose "$($MyInvocation.MyCommand.Name):: Writing key: $j"
							Add-Content -Path $outFile -Value "$j=$($InputObject[$i][$j])" -Encoding $Encoding
						}
						
					}
					Add-Content -Path $outFile -Value "" -Encoding $Encoding
				}
			}
			Write-Verbose "$($MyInvocation.MyCommand.Name):: Finished Writing to file: $path"
			if ($PassThru) { Return $outFile }
		}
		
		End
		{ Write-Verbose "$($MyInvocation.MyCommand.Name):: Function ended" }
	}
	#endregion Out-IniFile
	
	#region button-check
	function button-check
	{
		if (($toonsFile.Text -ne '') -and ($ShortcutsFolder.Text -ne ''))
		{
			$buttonBuildShortcuts.Enabled = $true
			$buttonBuildAutoHotKey.Enabled = $true
			$buttonBuildMQ2AutoLogin.Enabled = $true
			$buttonStartMissingToons.Enabled = $true
		}
		elseif (($toonsFile.Text -ne '') -and ($ShortcutsFolder.Text -eq ''))
		{
			$buttonBuildShortcuts.Enabled = $false
			$buttonBuildAutoHotKey.Enabled = $false
			$buttonBuildMQ2AutoLogin.Enabled = $true
			$buttonStartMissingToons.Enabled = $false
		}
		elseif (($toonsFile.Text -eq '') -and ($ShortcutsFolder.Text -ne ''))
		{
			$buttonBuildShortcuts.Enabled = $false
			$buttonBuildAutoHotKey.Enabled = $false
			$buttonBuildMQ2AutoLogin.Enabled = $false
			$buttonStartMissingToons.Enabled = $true
		}
		else
		{
			$buttonBuildShortcuts.Enabled = $false
			$buttonBuildAutoHotKey.Enabled = $false
			$buttonBuildMQ2AutoLogin.Enabled = $false
			$buttonStartMissingToons.Enabled = $false
			
		}
	}
	#endregion button-check
#endregion Source: Globals.ps1

#region Source: ChildForm.psf
function Show-ChildForm_psf
{
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formChildForm = New-Object 'System.Windows.Forms.Form'
	$buttonOK = New-Object 'System.Windows.Forms.Button'
	$buttonCancel = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	
	$formChildForm_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formChildForm.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$formChildForm.remove_Load($formChildForm_Load)
			$formChildForm.remove_Load($Form_StateCorrection_Load)
			$formChildForm.remove_Closing($Form_StoreValues_Closing)
			$formChildForm.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formChildForm.SuspendLayout()
	#
	# formChildForm
	#
	$formChildForm.Controls.Add($buttonOK)
	$formChildForm.Controls.Add($buttonCancel)
	$formChildForm.AutoScaleDimensions = '6, 13'
	$formChildForm.AutoScaleMode = 'Font'
	$formChildForm.ClientSize = '284, 262'
	$formChildForm.Margin = '4, 4, 4, 4'
	$formChildForm.Name = 'formChildForm'
	$formChildForm.StartPosition = 'CenterParent'
	$formChildForm.Text = 'Child Form'
	$formChildForm.add_Load($formChildForm_Load)
	#
	# buttonOK
	#
	$buttonOK.Anchor = 'Bottom, Right'
	$buttonOK.DialogResult = 'OK'
	$buttonOK.Location = '116, 227'
	$buttonOK.Name = 'buttonOK'
	$buttonOK.Size = '75, 23'
	$buttonOK.TabIndex = 1
	$buttonOK.Text = '&OK'
	$buttonOK.UseCompatibleTextRendering = $True
	$buttonOK.UseVisualStyleBackColor = $True
	#
	# buttonCancel
	#
	$buttonCancel.Anchor = 'Bottom, Right'
	$buttonCancel.CausesValidation = $False
	$buttonCancel.DialogResult = 'Cancel'
	$buttonCancel.Location = '197, 227'
	$buttonCancel.Name = 'buttonCancel'
	$buttonCancel.Size = '75, 23'
	$buttonCancel.TabIndex = 0
	$buttonCancel.Text = '&Cancel'
	$buttonCancel.UseCompatibleTextRendering = $True
	$buttonCancel.UseVisualStyleBackColor = $True
	$formChildForm.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formChildForm.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formChildForm.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formChildForm.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$formChildForm.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $formChildForm.ShowDialog()

}
#endregion Source: ChildForm.psf

#Start the application
Main ($CommandLine)
